export const LANGUAGES = {
  sq: 'Albanian',
  hy: 'Armenian',
  az: 'Azerbaijani',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  et: 'Estonian',
  fi: 'Finnish',
  fr: 'French',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  is: 'Icelandic',
  ga: 'Irish',
  he: 'Hebrew',
  it: 'Italian',
  lv: 'Latvian',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  mt: 'Maltese',
  cnr: 'Montenegrin', // ISO 639‑2
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt: 'Portuguese',
  sr: 'Serbian',
  sl: 'Slovenian',
  es: 'Spanish',
  sv: 'Swedish',
  uk: 'Ukrainian',
  en: 'English',
}

export const locales = Object.fromEntries(
  Object.keys(LANGUAGES).map((iso) => {
    return [iso, { required: true }]
  }),
)

// WARNING: we want to get rid of this file.
// Avoid using it or risk redoing code again and again and again
export const allowedLanguages = new Set(Object.keys(locales))
export const participatingCountries = new Set([
  'AL',
  'AM',
  'AT',
  'AU',
  'AZ',
  'BE',
  'CH',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'ES',
  'FI',
  'FR',
  'GB',
  'GE',
  'GR',
  'HR',
  'IE',
  'IL',
  'IS',
  'IT',
  'LT',
  'LU',
  'LV',
  'ME',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RS',
  'SE',
  'SI',
  'SM',
  'UA',
])
