export enum ParseError {
  'incorrectFieldType',
  'incorrectNodeType',
  'exceedsMaximum',
  'subceedsMinimum',
  'fieldDoesNotExist',
  'incorrectFormat',
  'referenceIsIncorrectType',
  'valueAndDefault',
  'defaultNotSupported',
  'multipleOperationsNotAllowed',
  'requiredFieldNotDefined',
  'languageNotSupported',
  'invalidJSON',
  'noLanguageFound',
  'cannotDeleteNodeFromModify',
  'numberOutOfBounds',
}
