import {
  safeInteger,
  minValue,
  number,
  picklist,
  pipe,
  union,
  custom,
  instance,
  string,
  boolean,
} from 'valibot'

export const compression = picklist(['none', 'deflate'])
export const natural = pipe(number(), safeInteger(), minValue(0))
export const positive = pipe(number(), minValue(0))
export const mime = union([
  picklist([
    'text/html',
    'text/plain',
    'text/markdown',
    'image/png',
    'image/jpeg',
    'video/mp4',
    'video/quicktime',
    'image/*',
    'video/*',
    'audio/*',
    '*/*',
  ]),
  custom<`${string}/${string}`>((v: string) => v.includes('/')),
])

export const format = picklist([
  'alpha',
  'alphaLocales',
  'alphanumeric',
  'alphanumericLocales',
  'ascii',
  'base32',
  'base58',
  'base64',
  'BIC',
  'btcAddress',
  'clike',
  'code',
  'creditCard',
  'css',
  'currency',
  'dataURI',
  'EAN',
  'email',
  'ethereumAddress',
  'FQDN',
  'hexadecimal',
  'hexColor',
  'HSL',
  'html',
  'IBAN',
  'identityCard',
  'IMEI',
  'IP',
  'IPRange',
  'ISBN',
  'ISIN',
  'ISO31661Alpha2',
  'ISO31661Alpha3',
  'ISO4217',
  'ISO6391',
  'ISO8601',
  'ISRC',
  'ISSN',
  'javascript',
  'json',
  'JWT',
  'latLong',
  'licensePlate',
  'lowercase',
  'luhnNumber',
  'MACAddress',
  'magnetURI',
  'markdown',
  'MD5',
  'mimeType',
  'mobilePhone',
  'mobilePhoneLocales',
  'octal',
  'password',
  'passportNumber',
  'port',
  'postalCode',
  'postalCodeLocales',
  'python',
  'RFC3339',
  'rgbColor',
  'rust',
  'semVer',
  'slug',
  'surrogatePair',
  'taxID',
  'typescript',
  'uppercase',
  'URL',
  'UUID',
  'VAT',
])

export const numberTypes = picklist([
  'number',
  'int8',
  'uint8',
  'int16',
  'uint16',
  'int32',
  'uint32',
])

export const vectorBaseTypes = picklist([
  ...numberTypes.options,
  'float32',
  'float64',
])

export const enumType = union([string(), boolean(), number()])
export const vectorType = union([
  instance(Int8Array),
  instance(Uint8Array),
  instance(Int16Array),
  instance(Uint16Array),
  instance(Int32Array),
  instance(Uint32Array),
  instance(Float32Array),
  instance(Float64Array),
])
