import { kCRCTable } from './crc32c_table.js'

/**
 * This code is a manual javascript translation of c code generated by
 * pycrc 0.7.1 (http://www.tty1.net/pycrc/). Command line used:
 * './pycrc.py --model=crc-32c --generate c --algorithm=table-driven'
 *
 * Adapted to use in Based.db  2025-02-17
 */

export function crc32c(val: string | Uint8Array): number {
  let data: Uint8Array
  let initial = 0

  if (typeof val === 'string') {
    // Convert string to Uint8Array using TextEncoder
    const encoder = new TextEncoder()
    data = encoder.encode(val)
  } else {
    data = val
  }

  let crc = (initial | 0) ^ -1

  for (let i = 0; i < data.length; i++) {
    crc = kCRCTable[(crc ^ data[i]) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ -1) >>> 0
}
