export const CONTENT_TYPE_JSON = 255
export const CONTENT_TYPE_UINT8_ARRAY = 254
export const CONTENT_TYPE_STRING = 253
export const CONTENT_TYPE_UNDEFINED = 252
export const CONTENT_TYPE_NULL = 251

export type CONTENT_TYPE =
  | typeof CONTENT_TYPE_JSON
  | typeof CONTENT_TYPE_UINT8_ARRAY
  | typeof CONTENT_TYPE_STRING
  | typeof CONTENT_TYPE_UNDEFINED
  | typeof CONTENT_TYPE_NULL

export const CONTENT_TYPE_JSON_U8 = new Uint8Array([CONTENT_TYPE_JSON])
export const CONTENT_TYPE_UINT8_ARRAY_U8 = new Uint8Array([
  CONTENT_TYPE_UINT8_ARRAY,
])
export const CONTENT_TYPE_STRING_U8 = new Uint8Array([CONTENT_TYPE_STRING])
export const CONTENT_TYPE_UNDEFINED_U8 = new Uint8Array([
  CONTENT_TYPE_UNDEFINED,
])
export const CONTENT_TYPE_NULL_U8 = new Uint8Array([CONTENT_TYPE_NULL])
