export default {
  locales: {
    en: { required: true },
    fr: { required: true },
    nl: { required: true },
    el: { required: true },
    he: { required: true },
    it: { required: true },
    lv: { required: true },
    lb: { required: true },
    ro: { required: true },
    sl: { required: true },
    es: { required: true },
    de: { required: true },
    cs: { required: true },
    et: { required: true },
  },
  props: {
    info: { type: 'text', format: 'html' },
    terms: {
      type: 'object',
      props: {
        title: { type: 'text' },
        introductionTitle: { type: 'text' },
        introductionText: { type: 'text', format: 'html' },
        rulesTitle: { type: 'text' },
        rulesText: { type: 'text', format: 'html' },
        procedureTitle: { type: 'text' },
        procedureText: { type: 'text', format: 'html' },
        noRefundsTitle: { type: 'text' },
        noRefundsText: { type: 'text', format: 'html' },
        dataTitle: { type: 'text' },
        dataText: { type: 'text', format: 'html' },
        voterRespTitle: { type: 'text' },
        voterRespText: { type: 'text', format: 'html' },
        votingWindowTitle: { type: 'text' },
        votingWindowText: { type: 'text', format: 'html' },
        generalCondTitle: { type: 'text' },
        generalCondText: { type: 'text', format: 'html' },
        jurisdictionTitle: { type: 'text' },
        jurisdictionText: { type: 'text', format: 'html' },
        changesTitle: { type: 'text' },
        changesText: { type: 'text', format: 'html' },
        lastUpdatedText: { type: 'text', format: 'html' },
        lastUpdated: { type: 'timestamp' },
      },
    },
    privacy: { type: 'text', format: 'html' },
    excludedCountries: { items: { ref: 'country' } },
    activeSequence: { ref: 'sequence' },
    coreDataLock: { type: 'boolean' },
    winner: { type: 'string' },
    dictionary: {
      type: 'object',
      props: {
        addVotes: { type: 'text' },
        appleMusic: { type: 'text' },
        appleMusicDisclaimer: { type: 'text' },
        buttonCall: { type: 'text' },
        buttonSMS: { type: 'text' },
        callNow: { type: 'text' },
        changeDescription: { type: 'text' },
        changeLocation: { type: 'text' },
        continue: { type: 'text' },
        cookieDisclaimer: { type: 'text' },
        imprint: { type: 'text' },
        overviewButton: { type: 'text' },
        phoneDescription: { type: 'text' },
        phoneInfo: { type: 'text' },
        phoneLocation: { type: 'text' },
        phoneSelection: { type: 'text' },
        privacy: { type: 'text' },
        selectionButton: { type: 'text' },
        selectionDescription: { type: 'text' },
        selectionSecure: { type: 'text' },
        selectionTitle: { type: 'text' },
        sendSMS: { type: 'text' },
        summaryButton: { type: 'text' },
        summaryCheckbox: { type: 'text' },
        summaryDisclaimer: { type: 'text' },
        summaryEmail: { type: 'text' },
        summaryProcessing: { type: 'text' },
        summaryProcessingMsg: { type: 'text' },
        summaryRefund: { type: 'text' },
        summarySecure: { type: 'text' },
        summarySelect: { type: 'text' },
        summaryTitle: { type: 'text' },
        summaryTotal: { type: 'text' },
        terms: { type: 'text' },
        thankYou: { type: 'text' },
        thankYouMax: { type: 'text' },
        thankYouMaxButton: { type: 'text' },
        thankYouOnline: { type: 'text' },
        thankYouOnlineButton: { type: 'text' },
        thankYouPhone: { type: 'text' },
        thankYouPhoneButton: { type: 'text' },
        votingInfo: { type: 'text' },
        whyImportant: { type: 'text' },
        days: { type: 'text' },
        hours: { type: 'text' },
        minutes: { type: 'text' },
        seconds: { type: 'text' },
      },
    },
    onboarding: {
      type: 'object',
      props: {
        restOfTheWorld: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        sanMarino: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        notAllowedSemi1: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        notAllowedSemi2: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        online: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        parentCode: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        phone: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        overseasCode: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
        noCode: {
          type: 'object',
          props: { title: { type: 'text' }, description: { type: 'text' } },
        },
      },
    },
  },
  types: {
    country: {
      props: {
        name: { type: 'alias' },
        currency: {
          enum: [
            'all',
            'amd',
            'aud',
            'azn',
            'chf',
            'czk',
            'dkk',
            'eur',
            'gbp',
            'gel',
            'ils',
            'isk',
            'mdl',
            'nok',
            'pln',
            'rsd',
            'sek',
            'uah',
          ],
        },
        isOverSeasTerritory: { type: 'boolean' },
        prequalifiedFor: { ref: 'round', prop: 'prequalifiedContries' },
        voteType: { enum: ['sms_text', 'sms_suffix', 'online', 'call_suffix'] },
        maxVotes: { type: 'uint8' },
        isTerritoryOf: { ref: 'country', prop: 'overseasTerritories' },
        price: { type: 'uint16' },
        destination: { type: 'string' },
        votingText: { type: 'text' },
        votingLegal: { type: 'text' },
        overseasTerritories: {
          readOnly: true,
          items: { ref: 'country', prop: 'isTerritoryOf' },
        },
        votingRounds: {
          readOnly: true,
          items: { ref: 'round', prop: 'canVote' },
        },
        contestants: {
          readOnly: true,
          items: { ref: 'contestant', prop: 'country' },
        },
      },
    },
    sequence: {
      props: {
        name: { type: 'alias', readOnly: true },
        displayName: { type: 'string' },
        goLiveTime: { type: 'timestamp' },
        recapVideo: { ref: 'file', prop: 'sequenceRecapVideo' },
        recapTitle: { type: 'text' },
        title: { type: 'text' },
        description: { type: 'text' },
        countdown: { type: 'timestamp' },
        round: { ref: 'round', prop: 'sequences' },
        row: {
          props: {
            title: { type: 'text' },
            description: { type: 'text' },
            countdown: { type: 'timestamp' },
          },
        },
      },
    },
    round: {
      props: {
        name: { type: 'alias' },
        displayName: { type: 'string' },
        contestants: { items: { ref: 'contestant', prop: 'rounds' } },
        canVote: { items: { ref: 'country', prop: 'votingRounds' } },
        prequalifiedContries: {
          items: { ref: 'country', prop: 'prequalifiedFor' },
        },
        votes: { items: { ref: 'vote', prop: 'round' } },
        createdBy: { ref: 'user', prop: 'createdRounds' },
        sequences: {
          readOnly: true,
          items: { ref: 'sequence', prop: 'round' },
        },
      },
    },
    contestant: {
      props: {
        name: { type: 'string' },
        ddi: { type: 'alias' },
        song: { type: 'string' },
        lyrics: { type: 'string', format: 'multiline' },
        country: { ref: 'country', prop: 'contestants' },
        image: { ref: 'file', prop: 'contestant_image' },
        video: { ref: 'file', prop: 'contestant_video' },
        thankYouVideos: { items: { ref: 'file', prop: 'contestant_ty_video' } },
        rounds: {
          readOnly: true,
          items: { ref: 'round', prop: 'contestants' },
        },
      },
    },
    user: {
      props: {
        name: { type: 'string' },
        email: { type: 'alias', format: 'email' },
        role: { enum: ['admin', 'translator', 'viewer'] },
        translatorOf: { items: { ref: 'language', prop: 'translators' } },
        avatar: { ref: 'file', prop: 'avatarOf' },
        currentToken: { type: 'alias' },
        status: { enum: ['login', 'clear', 'invited'] },
        createdAt: { type: 'timestamp', on: 'create' },
        updatedAt: { type: 'timestamp', on: 'update' },
        invited: { items: { ref: 'user', prop: 'invitedBy' } },
        invitedBy: { ref: 'user', prop: 'invited' },
        inactive: { type: 'boolean' },
        createdRounds: {
          readOnly: true,
          items: { ref: 'round', prop: 'createdBy' },
        },
      },
    },
    file: {
      props: {
        name: { type: 'string' },
        src: { type: 'string', format: 'URL' },
        mimeType: { type: 'string' },
        description: { type: 'string' },
        progress: { type: 'number', display: 'ratio' },
        status: { enum: ['uploading', 'transcoding', 'ready', 'error'] },
        statusText: { type: 'string' },
        size: { type: 'int32' },
        createdAt: { type: 'timestamp', on: 'create' },
        updatedAt: { type: 'timestamp', on: 'update' },
        thumbnail: { type: 'string', format: 'URL' },
        hls: { type: 'string', format: 'URL' },
        dash: { type: 'string', format: 'URL' },
        videoPreview: { type: 'string', format: 'URL' },
        selvaId: { type: 'alias', readOnly: true },
        sequenceRecapVideo: {
          readOnly: true,
          items: { ref: 'sequence', prop: 'recapVideo' },
        },
        contestant_image: {
          readOnly: true,
          items: { ref: 'contestant', prop: 'image' },
        },
        contestant_video: {
          readOnly: true,
          items: { ref: 'contestant', prop: 'video' },
        },
        contestant_ty_video: {
          readOnly: true,
          items: { ref: 'contestant', prop: 'thankYouVideos' },
        },
        avatarOf: { readOnly: true, items: { ref: 'user', prop: 'avatar' } },
      },
    },
    language: {
      props: {
        iso: { type: 'alias', required: true },
        name: { type: 'string' },
        completionStatus: { type: 'number', min: 0, max: 1 },
        translators: { items: { ref: 'user', prop: 'translatorOf' } },
      },
    },
    payment: {
      props: {
        confirmationTokenId: { type: 'string' },
        intentId: { type: 'alias' },
        fingerprint: { type: 'alias' },
        amount: { type: 'number' },
        currency: { type: 'string' },
        status: {
          enum: [
            'requested',
            'ready_for_payment',
            'intent_success',
            'intent_failed',
            'webhook_success',
            'webhook_failed',
            'capture_captured',
            'capture_canceled',
          ],
        },
        bankCountry: { type: 'string' },
        failReason: { type: 'string' },
        vote: { ref: 'vote', prop: 'payment' },
        createdAt: { type: 'timestamp', on: 'create' },
        updatedAt: { type: 'timestamp', on: 'update' },
      },
    },
    vote: {
      props: {
        fingerprintAndRound: { type: 'alias', required: true },
        payment: { ref: 'payment', prop: 'vote', required: true },
        round: { ref: 'round', prop: 'votes', required: true },
        ddi: {
          props: {
            ddi1: { type: 'uint8' },
            ddi2: { type: 'uint8' },
            ddi3: { type: 'uint8' },
            ddi4: { type: 'uint8' },
            ddi5: { type: 'uint8' },
            ddi6: { type: 'uint8' },
            ddi7: { type: 'uint8' },
            ddi8: { type: 'uint8' },
            ddi9: { type: 'uint8' },
            ddi10: { type: 'uint8' },
            ddi11: { type: 'uint8' },
            ddi12: { type: 'uint8' },
            ddi13: { type: 'uint8' },
            ddi14: { type: 'uint8' },
            ddi15: { type: 'uint8' },
            ddi16: { type: 'uint8' },
            ddi17: { type: 'uint8' },
            ddi18: { type: 'uint8' },
            ddi19: { type: 'uint8' },
            ddi20: { type: 'uint8' },
          },
        },
      },
    },
  },
}
