export const onboarding = {
  online: {
    title: {
      en: '{ONBOARDING_TITLE_GENERIC}',
      sq: '{ONBOARDING_TITLE_GENERIC}',
      hy: '{ONBOARDING_TITLE_GENERIC}',
      az: '{ONBOARDING_TITLE_GENERIC}',
      hr: '{ONBOARDING_TITLE_GENERIC}',
      cs: '{ONBOARDING_TITLE_GENERIC}',
      da: '{ONBOARDING_TITLE_GENERIC}',
      et: '{ONBOARDING_TITLE_GENERIC}',
      fi: '{ONBOARDING_TITLE_GENERIC}',
      fr: '{ONBOARDING_TITLE_GENERIC}',
      ka: '{ONBOARDING_TITLE_GENERIC}',
      de: '{ONBOARDING_TITLE_GENERIC}',
      el: '{ONBOARDING_TITLE_GENERIC}',
      is: '{ONBOARDING_TITLE_GENERIC}',
      ga: '{ONBOARDING_TITLE_GENERIC}',
      he: '{ONBOARDING_TITLE_GENERIC}',
      it: '{ONBOARDING_TITLE_GENERIC}',
      lv: '{ONBOARDING_TITLE_GENERIC}',
      lt: '{ONBOARDING_TITLE_GENERIC}',
      lb: '{ONBOARDING_TITLE_GENERIC}',
      mt: '{ONBOARDING_TITLE_GENERIC}',
      cnr: '{ONBOARDING_TITLE_GENERIC}',
      nl: '{ONBOARDING_TITLE_GENERIC}',
      no: '{ONBOARDING_TITLE_GENERIC}',
      pl: '{ONBOARDING_TITLE_GENERIC}',
      pt: '{ONBOARDING_TITLE_GENERIC}',
      sr: '{ONBOARDING_TITLE_GENERIC}',
      sl: '{ONBOARDING_TITLE_GENERIC}',
      es: '{ONBOARDING_TITLE_GENERIC}',
      sv: '{ONBOARDING_TITLE_GENERIC}',
      uk: '{ONBOARDING_TITLE_GENERIC}',
    },
    description: {
      en: 'In order to cast votes on behalf of {COUNTRY}, you will need a payment card that was issued in {COUNTRY}.',
      sq: "Për të hedhur vota në emër të {COUNTRY}, do t'ju duhet një kartë pagese që është lëshuar në {COUNTRY}.",
      hy: '{COUNTRY}-ի անունից քվեարկելու համար ձեզ անհրաժեշտ կլինի {COUNTRY}-ում թողարկված վճարային քարտ:',
      az: '{COUNTRY} adından səs vermək üçün sizə {COUNTRY}-də verilmiş ödəniş kartı lazım olacaq.',
      hr: 'Kako biste glasali u ime {COUNTRY}, trebat će vam platna kartica izdana u {COUNTRY}.',
      cs: 'Pro hlasování za {COUNTRY} potřebujete platební kartu vydanou v {COUNTRY}.',
      da: 'For at afgive stemmer på vegne af {COUNTRY}, skal du bruge et betalingskort, der er udstedt i {COUNTRY}.',
      et: 'Et hääletada {COUNTRY} nimel, on vaja maksekaarti, mis on väljastatud {COUNTRY}-s.',
      fi: 'Voidaksesi äänestää maan {COUNTRY} puolesta tarvitset maksukortin, joka on myönnetty maassa {COUNTRY}.',
      fr: "Pour voter au nom de {COUNTRY}, vous aurez besoin d'une carte de paiement émise dans {COUNTRY}.",
      ka: '{COUNTRY}-ის სახელით ხმის მისაცემად დაგჭირდებათ გადახდის ბარათი, რომელიც გაცემულია {COUNTRY}-ში.',
      de: 'Um Stimmen im Namen von {COUNTRY} abzugeben, benötigen Sie eine Zahlungskarte, die in {COUNTRY} ausgestellt wurde.',
      el: 'Για να ψηφίσετε εκ μέρους της {COUNTRY}, θα χρειαστείτε μια κάρτα πληρωμής που έχει εκδοθεί στην {COUNTRY}.',
      is: 'Til að greiða atkvæði fyrir hönd {COUNTRY} þarftu greiðslukort sem gefið er út í {COUNTRY}.',
      ga: 'Chun vótaí a chaitheamh thar ceann {COUNTRY}, beidh cárta íocaíochta uait a eisíodh i {COUNTRY}.',
      he: 'כדי להצביע בשם {COUNTRY}, תזדקקו לכרטיס תשלום שהונפק ב{COUNTRY}.',
      it: 'Per votare per conto di {COUNTRY}, avrai bisogno di una carta di pagamento emessa in {COUNTRY}.',
      lv: 'Lai balsotu {COUNTRY} vārdā, jums būs nepieciešama maksājumu karte, kas izdota {COUNTRY}.',
      lt: 'Norint balsuoti {COUNTRY} vardu, jums reikės mokėjimo kortelės, išduotos {COUNTRY}.',
      lb: 'Fir am Numm vu(n) {COUNTRY} ofzestëmmen, braucht Dir eng Bezuelkaart, déi a(n) {COUNTRY} ausgestallt gouf.',
      mt: "Sabiex titfa' voti f'isem {COUNTRY}, ser ikollok bżonn karta tal-ħlas li tkun inħarġet f'{COUNTRY}.",
      cnr: 'Da biste glasali u ime {COUNTRY}, biće vam potrebna platna kartica izdata u {COUNTRY}.',
      nl: 'Om namens {COUNTRY} te stemmen, heb je een betaalkaart nodig die is uitgegeven in {COUNTRY}.',
      no: 'For å avgi stemmer på vegne av {COUNTRY}, trenger du et betalingskort som er utstedt i {COUNTRY}.',
      pl: 'Aby oddać głosy w imieniu {COUNTRY}, potrzebujesz karty płatniczej wydanej w {COUNTRY}.',
      pt: 'Para votar em nome de {COUNTRY}, precisará de um cartão de pagamento emitido em {COUNTRY}.',
      sr: 'Да бисте гласали у име {COUNTRY}, биће вам потребна платна картица издата у {COUNTRY}.',
      sl: 'Za glasovanje v imenu države {COUNTRY} potrebujete plačilno kartico, izdano v državi {COUNTRY}.',
      es: 'Para votar en nombre de {COUNTRY}, necesitarás una tarjeta de pago emitida en {COUNTRY}.',
      sv: 'För att rösta för {COUNTRY} behöver du ett betalkort som är utfärdat i {COUNTRY}.',
      uk: 'Щоб проголосувати від імені {COUNTRY}, вам знадобиться платіжна картка, видана в {COUNTRY}.',
    },
  },
  phone: {
    title: {
      en: '{ONBOARDING_TITLE_GENERIC}',
      sq: '{ONBOARDING_TITLE_GENERIC}',
      hy: '{ONBOARDING_TITLE_GENERIC}',
      az: '{ONBOARDING_TITLE_GENERIC}',
      hr: '{ONBOARDING_TITLE_GENERIC}',
      cs: '{ONBOARDING_TITLE_GENERIC}',
      da: '{ONBOARDING_TITLE_GENERIC}',
      et: '{ONBOARDING_TITLE_GENERIC}',
      fi: '{ONBOARDING_TITLE_GENERIC}',
      fr: '{ONBOARDING_TITLE_GENERIC}',
      ka: '{ONBOARDING_TITLE_GENERIC}',
      de: '{ONBOARDING_TITLE_GENERIC}',
      el: '{ONBOARDING_TITLE_GENERIC}',
      is: '{ONBOARDING_TITLE_GENERIC}',
      ga: '{ONBOARDING_TITLE_GENERIC}',
      he: '{ONBOARDING_TITLE_GENERIC}',
      it: '{ONBOARDING_TITLE_GENERIC}',
      lv: '{ONBOARDING_TITLE_GENERIC}',
      lt: '{ONBOARDING_TITLE_GENERIC}',
      lb: '{ONBOARDING_TITLE_GENERIC}',
      mt: '{ONBOARDING_TITLE_GENERIC}',
      cnr: '{ONBOARDING_TITLE_GENERIC}',
      nl: '{ONBOARDING_TITLE_GENERIC}',
      no: '{ONBOARDING_TITLE_GENERIC}',
      pl: '{ONBOARDING_TITLE_GENERIC}',
      pt: '{ONBOARDING_TITLE_GENERIC}',
      sr: '{ONBOARDING_TITLE_GENERIC}',
      sl: '{ONBOARDING_TITLE_GENERIC}',
      es: '{ONBOARDING_TITLE_GENERIC}',
      sv: '{ONBOARDING_TITLE_GENERIC}',
      uk: '{ONBOARDING_TITLE_GENERIC}',
    },
    description: {
      en: 'In order to cast votes on behalf of {COUNTRY}, you will need a SIM card with a phone number from {COUNTRY} ({DIAL}).',
      sq: "Për të hedhur vota në emër të {COUNTRY}, do t'ju duhet një kartë SIM me një numër telefoni nga {COUNTRY} ({DIAL}).",
      hy: '{COUNTRY}-ի անունից քվեարկելու համար ձեզ անհրաժեշտ կլինի SIM քարտ՝ {COUNTRY}-ի հեռախոսահամարով ({DIAL})։',
      az: '{COUNTRY} adından səs vermək üçün sizə {COUNTRY} ({DIAL}) telefon nömrəsi olan SİM kart lazım olacaq.',
      hr: 'Kako biste glasali u ime {COUNTRY}, trebat će vam SIM kartica s telefonskim brojem iz {COUNTRY} ({DIAL}).',
      cs: 'Pro hlasování jménem {COUNTRY} potřebujete SIM kartu s telefonním číslem z {COUNTRY} ({DIAL}).',
      da: 'For at afgive stemmer på vegne af {COUNTRY}, skal du bruge et SIM-kort med et telefonnummer fra {COUNTRY} ({DIAL}).',
      et: 'Et hääletada {COUNTRY} nimel, on vaja SIM-kaarti telefoninumbriga {COUNTRY}-st ({DIAL}).',
      fi: 'Voidaksesi äänestää maan {COUNTRY} puolesta tarvitset SIM-kortin, jossa on puhelinnumero maasta {COUNTRY} ({DIAL}).',
      fr: "Pour voter au nom de {COUNTRY}, vous aurez besoin d'une carte SIM avec un numéro de téléphone de {COUNTRY} ({DIAL}).",
      ka: '{COUNTRY}-ის სახელით ხმის მისაცემად დაგჭირდებათ SIM ბარათი {COUNTRY}-ის ({DIAL}) ტელეფონის ნომრით.',
      de: 'Um Stimmen im Namen von {COUNTRY} abzugeben, benötigen Sie eine SIM-Karte mit einer Telefonnummer aus {COUNTRY} ({DIAL}).',
      el: 'Για να ψηφίσετε εκ μέρους της {COUNTRY}, θα χρειαστείτε μια κάρτα SIM με τηλεφωνικό αριθμό από την {COUNTRY} ({DIAL}).',
      is: 'Til að greiða atkvæði fyrir hönd {COUNTRY} þarftu SIM-kort með símanúmeri frá {COUNTRY} ({DIAL}).',
      ga: 'Chun vótaí a chaitheamh thar ceann {COUNTRY}, beidh cárta SIM uait le huimhir theileafóin ó {COUNTRY} ({DIAL}).',
      he: 'כדי להצביע בשם {COUNTRY}, תזדקקו לכרטיס SIM עם מספר טלפון מ{COUNTRY} ({DIAL}).',
      it: 'Per votare per conto di {COUNTRY}, avrai bisogno di una scheda SIM con un numero di telefono da {COUNTRY} ({DIAL}).',
      lv: 'Lai balsotu {COUNTRY} vārdā, jums būs nepieciešama SIM karte ar {COUNTRY} tālruņa numuru ({DIAL}).',
      lt: 'Norint balsuoti {COUNTRY} vardu, jums reikės SIM kortelės su telefono numeriu iš {COUNTRY} ({DIAL}).',
      lb: 'Fir am Numm vu(n) {COUNTRY} ofzestëmmen, braucht Dir eng SIM-Kaart mat enger Telefonsnummer aus {COUNTRY} ({DIAL}).',
      mt: "Sabiex titfa' voti f'isem {COUNTRY}, ser ikollok bżonn SIM card b'numru tat-telefon minn {COUNTRY} ({DIAL}).",
      cnr: 'Da biste glasali u ime {COUNTRY}, biće vam potrebna SIM kartica sa telefonskim brojem iz {COUNTRY} ({DIAL}).',
      nl: 'Om namens {COUNTRY} te stemmen, heb je een SIM-kaart nodig met een telefoonnummer uit {COUNTRY} ({DIAL}).',
      no: 'For å avgi stemmer på vegne av {COUNTRY}, trenger du et SIM-kort med et telefonnummer fra {COUNTRY} ({DIAL}).',
      pl: 'Aby oddać głosy w imieniu {COUNTRY}, potrzebujesz karty SIM z numerem telefonu z {COUNTRY} ({DIAL}).',
      pt: 'Para votar em nome de {COUNTRY}, precisará de um cartão SIM com um número de telefone de {COUNTRY} ({DIAL}).',
      sr: 'Да бисте гласали у име {COUNTRY}, биће вам потребна СИМ картица са телефонским бројем из {COUNTRY} ({DIAL}).',
      sl: 'Za glasovanje v imenu države {COUNTRY} potrebujete kartico SIM s telefonsko številko iz države {COUNTRY} ({DIAL}).',
      es: 'Para votar en nombre de {COUNTRY}, necesitarás una tarjeta SIM con un número de teléfono de {COUNTRY} ({DIAL}).',
      sv: 'För att rösta för {COUNTRY} behöver du ett SIM-kort med ett telefonnummer från {COUNTRY} ({DIAL}).',
      uk: 'Щоб проголосувати від імені {COUNTRY}, вам знадобиться SIM-карта з телефонним номером {COUNTRY} ({DIAL}).',
    },
  },
  nonParticipating: {
    title: {
      en: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      sq: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      hy: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      az: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      hr: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      cs: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      da: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      et: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      fi: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      fr: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      ka: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      de: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      el: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      is: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      ga: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      he: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      it: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      lv: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      lt: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      lb: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      mt: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      cnr: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      nl: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      no: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      pl: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      pt: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      sr: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      sl: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      es: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      sv: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
      uk: '{ONBOARDING_TITLE_NON_PARTICIPATING}',
    },
    description: {
      en: 'In order to cast votes from “Rest of the World”, you will need a payment card that was issued in a non-participating country.',
      sq: "Për të hedhur vota nga “Pjesa tjetër e Botës”, do t'ju duhet një kartë pagese që është lëshuar në një vend jo-pjesëmarrës.",
      hy: '«Աշխարհի մնացած մասից» քվեարկելու համար ձեզ անհրաժեշտ կլինի վճարային քարտ, որը թողարկվել է չմասնակցող երկրում:',
      az: '“Dünyanın Qalan Hissəsi”ndən səs vermək üçün sizə iştirak etməyən bir ölkədə verilmiş ödəniş kartı lazım olacaq.',
      hr: 'Kako biste glasali u ime “Ostatka svijeta”, trebat će vam platna kartica izdana u zemlji koja ne sudjeluje.',
      cs: 'Pro hlasování jménem "Zbytku světa" potřebujete platební kartu vydanou v neúčastnické zemi.',
      da: 'For at afgive stemmer fra “Resten af Verden”, skal du bruge et betalingskort, der er udstedt i et ikke-deltagende land.',
      et: 'Et hääletada "Ülejäänud maailma" nimel, on vaja maksekaarti, mis on väljastatud mitteosalevas riigis.',
      fi: 'Voidaksesi äänestää ”Muun maailman” puolesta tarvitset maksukortin, joka on myönnetty ei-osallistuvassa maassa.',
      fr: 'Pour voter au nom du "Reste du Monde", vous aurez besoin d\'une carte de paiement émise dans un pays non participant.',
      ka: '„დანარჩენი მსოფლიოდან“ ხმის მისაცემად დაგჭირდებათ გადახდის ბარათი, რომელიც გაცემულია არამონაწილე ქვეყანაში.',
      de: 'Um Stimmen für den „Rest der Welt“ abzugeben, benötigen Sie eine Zahlungskarte, die in einem nicht teilnehmenden Land ausgestellt wurde.',
      el: 'Για να ψηφίσετε εκ μέρους του "Υπόλοιπου Κόσμου", θα χρειαστείτε μια κάρτα πληρωμής που έχει εκδοθεί σε μια μη συμμετέχουσα χώρα.',
      is: 'Til að greiða atkvæði fyrir „Rest of the World“ þarftu greiðslukort sem gefið er út í landi sem tekur ekki þátt.',
      ga: 'Chun vótaí a chaitheamh ó “An Chuid Eile den Domhan”, beidh cárta íocaíochta uait a eisíodh i dtír neamh-rannpháirteach.',
      he: 'כדי להצביע מ"שאר העולם", תזדקקו לכרטיס תשלום שהונפק במדינה שאינה משתתפת.',
      it: 'Per votare per conto del "Resto del Mondo", avrai bisogno di una carta di pagamento emessa in un paese non partecipante.',
      lv: 'Lai balsotu kā “Pārējā pasaule”, jums būs nepieciešama maksājumu karte, kas izdota valstī, kura nepiedalās konkursā.',
      lt: 'Norint balsuoti iš „Likusių pasaulio šalių“, jums reikės mokėjimo kortelės, išduotos nedalyvaujančioje šalyje.',
      lb: 'Fir am Numm vum „Rescht vun der Welt“ ofzestëmmen, braucht Dir eng Bezuelkaart, déi an engem net-participéierende Land ausgestallt gouf.',
      mt: "Sabiex titfa' voti minn “Bqija tad-Dinja”, ser ikollok bżonn karta tal-ħlas li tkun inħarġet f'pajjiż mhux parteċipanti.",
      cnr: 'Da biste glasali u ime “Ostatka svijeta”, biće vam potrebna platna kartica izdata u zemlji koja ne učestvuje.',
      nl: 'Om stemmen uit te brengen namens de "Rest van de Wereld", heb je een betaalkaart nodig die is uitgegeven in een niet-deelnemend land.',
      no: 'For å avgi stemmer fra “Resten av verden”, trenger du et betalingskort som er utstedt i et ikke-deltakende land.',
      pl: 'Aby oddać głosy z „Reszty Świata”, potrzebujesz karty płatniczej wydanej w kraju nieuczestniczącym.',
      pt: 'Para votar em nome do “Resto do Mundo”, precisará de um cartão de pagamento emitido num país não participante.',
      sr: 'Да бисте гласали у име „Остатка света“, биће вам потребна платна картица издата у земљи која не учествује.',
      sl: 'Za oddajo glasov v imenu "Ostanka sveta" potrebujete plačilno kartico, izdano v državi, ki ne sodeluje v tekmovanju.',
      es: 'Para votar en nombre del "Resto del Mundo", necesitarás una tarjeta de pago emitida en un país no participante.',
      sv: 'För att rösta från ”Resten av världen” behöver du ett betalkort som är utfärdat i ett icke-deltagande land.',
      uk: 'Щоб проголосувати від «Решти світу», вам знадобиться платіжна картка, видана в країні, яка не бере участі.',
    },
  },
  notAllowedSemi1: {
    title: {
      en: '{ONBOARDING_TITLE_GENERIC}',
      sq: '{ONBOARDING_TITLE_GENERIC}',
      hy: '{ONBOARDING_TITLE_GENERIC}',
      az: '{ONBOARDING_TITLE_GENERIC}',
      hr: '{ONBOARDING_TITLE_GENERIC}',
      cs: '{ONBOARDING_TITLE_GENERIC}',
      da: '{ONBOARDING_TITLE_GENERIC}',
      et: '{ONBOARDING_TITLE_GENERIC}',
      fi: '{ONBOARDING_TITLE_GENERIC}',
      fr: '{ONBOARDING_TITLE_GENERIC}',
      ka: '{ONBOARDING_TITLE_GENERIC}',
      de: '{ONBOARDING_TITLE_GENERIC}',
      el: '{ONBOARDING_TITLE_GENERIC}',
      is: '{ONBOARDING_TITLE_GENERIC}',
      ga: '{ONBOARDING_TITLE_GENERIC}',
      he: '{ONBOARDING_TITLE_GENERIC}',
      it: '{ONBOARDING_TITLE_GENERIC}',
      lv: '{ONBOARDING_TITLE_GENERIC}',
      lt: '{ONBOARDING_TITLE_GENERIC}',
      lb: '{ONBOARDING_TITLE_GENERIC}',
      mt: '{ONBOARDING_TITLE_GENERIC}',
      cnr: '{ONBOARDING_TITLE_GENERIC}',
      nl: '{ONBOARDING_TITLE_GENERIC}',
      no: '{ONBOARDING_TITLE_GENERIC}',
      pl: '{ONBOARDING_TITLE_GENERIC}',
      pt: '{ONBOARDING_TITLE_GENERIC}',
      sr: '{ONBOARDING_TITLE_GENERIC}',
      sl: '{ONBOARDING_TITLE_GENERIC}',
      es: '{ONBOARDING_TITLE_GENERIC}',
      sv: '{ONBOARDING_TITLE_GENERIC}',
      uk: '{ONBOARDING_TITLE_GENERIC}',
    },
    description: {
      en: 'Unfortunately, viewers from {COUNTRY} are not eligible to vote during the First Semi-Final as determined in the Allocation Draw. Please join us again and vote during the Second Semi-Final starting {SEMI2_SHOWTIME} and the Grand Final starting {FINAL_SHOWTIME}!',
      sq: 'Fatkeqësisht, shikuesit nga {COUNTRY} nuk janë të kualifikuar për të votuar gjatë Gjysmëfinales së Parë siç është përcaktuar në Shortin e Ndarjes. Ju lutemi bashkohuni përsëri me ne dhe votoni gjatë Gjysmëfinales së Dytë duke filluar {SEMI2_SHOWTIME} dhe Finales së Madhe duke filluar {FINAL_SHOWTIME}!',
      hy: 'Ցավոք, {COUNTRY}-ի հեռուստադիտողները իրավասու չեն քվեարկել Առաջին կիսաեզրափակչի ընթացքում՝ համաձայն Բաշխման վիճակահանության: Խնդրում ենք նորից միանալ մեզ և քվեարկել Երկրորդ կիսաեզրափակչի ընթացքում՝ սկսած {SEMI2_SHOWTIME} և Մեծ եզրափակչի ընթացքում՝ սկսած {FINAL_SHOWTIME}:',
      az: 'Təəssüf ki, {COUNTRY} ölkəsindən olan tamaşaçılar Bölüşdürmə Püşkatmasında müəyyən edildiyi kimi Birinci Yarımfinal zamanı səs verə bilməzlər. Lütfən, {SEMI2_SHOWTIME} başlayan İkinci Yarımfinal və {FINAL_SHOWTIME} başlayan Böyük Final zamanı yenidən bizə qoşulun və səs verin!',
      hr: 'Nažalost, gledatelji iz {COUNTRY} nemaju pravo glasati tijekom Prvog polufinala kako je određeno u Alokacijskom ždrijebu. Molimo vas da nam se ponovno pridružite i glasate tijekom Drugog polufinala koje počinje {SEMI2_SHOWTIME} i Velikog finala koje počinje {FINAL_SHOWTIME}!',
      cs: 'Bohužel diváci z {COUNTRY} nemají právo hlasovat během prvního semifinále, jak bylo určeno ve výběru skupin. Připojte se k nám znovu a hlasujte během druhého semifinále, které začíná {SEMI2_SHOWTIME}, a velkého finále, které začíná {FINAL_SHOWTIME}!',
      da: 'Desværre er seere fra {COUNTRY} ikke berettigede til at stemme under den Første Semifinale som bestemt ved lodtrækningen. Vær venlig at deltage igen og stemme under den Anden Semifinale, der starter {SEMI2_SHOWTIME}, og den Store Finale, der starter {FINAL_SHOWTIME}!',
      et: 'Kahjuks ei ole {COUNTRY} vaatajatel loosi alusel õigust hääletada Esimeses poolfinaalis. Palun liituge meiega uuesti ja hääletage Teises poolfinaalis alates {SEMI2_SHOWTIME} ja Suures Finaalis alates {FINAL_SHOWTIME}!',
      fi: 'Valitettavasti katsojat maasta {COUNTRY} eivät ole oikeutettuja äänestämään Ensimmäisessä semifinaalissa Allokaatioarvonnan mukaisesti. Liitythän seuraamme uudelleen ja äänestä Toisessa semifinaalissa alkaen {SEMI2_SHOWTIME} ja Suuressa finaalissa alkaen {FINAL_SHOWTIME}!',
      fr: 'Malheureusement, les téléspectateurs de {COUNTRY} ne sont pas éligibles pour voter lors de la Première Demi-finale, comme déterminé lors du Tirage au sort. Merci de nous rejoindre à nouveau et de voter lors de la Deuxième Demi-finale à partir de {SEMI2_SHOWTIME} et de la Grande Finale à partir de {FINAL_SHOWTIME} !',
      ka: 'სამწუხაროდ, {COUNTRY}-ის მაყურებლებს არ აქვთ უფლება ხმის მიცემის პირველ ნახევარფინალში, განაწილების წილისყრის მიხედვით. გთხოვთ, შემოგვიერთდეთ კვლავ და ხმა მიეცით მეორე ნახევარფინალის დროს, რომელიც იწყება {SEMI2_SHOWTIME}, და გრანდ ფინალის დროს, რომელიც იწყება {FINAL_SHOWTIME}!',
      de: 'Leider sind Zuschauer:innen aus {COUNTRY} nicht berechtigt, während des Ersten Halbfinales abzustimmen, wie im Allocation Draw bestimmt wurde. Bitte schließen Sie sich uns wieder an und stimmen Sie während des Zweiten Halbfinales ab {SEMI2_SHOWTIME} und dem Großen Finale ab {FINAL_SHOWTIME}!',
      el: 'Δυστυχώς, οι τηλεθεατές από την {COUNTRY} δεν έχουν δικαίωμα να ψηφίσουν κατά τον Πρώτο Ημιτελικό όπως καθορίστηκε στην Κλήρωση Κατανομής. Παρακαλούμε ελάτε ξανά μαζί μας και ψηφίστε κατά τη διάρκεια του Δεύτερου Ημιτελικού που ξεκινά {SEMI2_SHOWTIME} και του Μεγάλου Τελικού που ξεκινά {FINAL_SHOWTIME}!',
      is: 'Því miður eru áhorfendur frá {COUNTRY} ekki gjaldgengir til að kjósa í Fyrri undanúrslitum eins og ákveðið var í úthlutunardrættinum. Vinsamlegast vertu með okkur aftur og kjóstu í Seinni undanúrslitum sem hefjast {SEMI2_SHOWTIME} og Stóru úrslitunum sem hefjast {FINAL_SHOWTIME}!',
      ga: 'Ar an drochuair, níl lucht féachana ó {COUNTRY} i dteideal vótáil le linn an Chéad Chluiche Leathcheannais mar a cinneadh sa Tarraingt Leithdháilte. Bí linn arís agus vótáil le linn an Dara Cluiche Leathcheannais ag tosú {SEMI2_SHOWTIME} agus an Grand Final ag tosú {FINAL_SHOWTIME}!',
      he: 'לצערנו, צופים מ{COUNTRY} אינם רשאים להצביע במהלך חצי הגמר הראשון כפי שנקבע בהגרלת החלוקה. אנא הצטרפו אלינו שוב והצביעו במהלך חצי הגמר השני שיתחיל {SEMI2_SHOWTIME} והגמר הגדול שיתחיל {FINAL_SHOWTIME}!',
      it: 'Purtroppo, gli spettatori da {COUNTRY} non sono idonei a votare durante la Prima Semifinale come determinato nel Sorteggio di Allocazione. Per favore, unisciti a noi di nuovo e vota durante la Seconda Semifinale a partire da {SEMI2_SHOWTIME} e la Grand Finale a partire da {FINAL_SHOWTIME}!',
      lv: 'Diemžēl skatītāji no {COUNTRY} nav tiesīgi balsot Pirmajā pusfinālā, kā noteikts Sadalījuma izlozē. Lūdzu, pievienojieties mums atkal un balsojiet Otrā pusfināla laikā, kas sākas {SEMI2_SHOWTIME}, un Lielajā finālā, kas sākas {FINAL_SHOWTIME}!',
      lt: 'Deja, žiūrovai iš {COUNTRY} negali balsuoti Pirmajame pusfinalyje, kaip nustatyta Paskirstymo burtų traukimo metu. Prašome prisijungti prie mūsų vėl ir balsuoti Antrajame pusfinalyje, pradedant {SEMI2_SHOWTIME}, ir Didžiajame finale, pradedant {FINAL_SHOWTIME}!',
      lb: 'Leider sinn Zuschauer aus {COUNTRY} net berechtegt, während der Éischter Halleffinall ofzestëmmen, wéi et am Allocation Draw bestëmmt gouf. Maacht w.e.g. erëm mat a stëmmt während der Zweeter Halleffinall of {SEMI2_SHOWTIME} an der Grousser Finall of {FINAL_SHOWTIME}!',
      mt: 'Sfortunatament, it-telespettaturi minn {COUNTRY} mhumiex eliġibbli biex jivvutaw matul l-Ewwel Semi-Finali kif determinat fit-Telfa tal-Allokazzjoni. Jekk jogħġbok ingħaqad magħna mill-ġdid u vvota matul it-Tieni Semi-Finali li tibda {SEMI2_SHOWTIME} u l-Finali l-Kbira li tibda {FINAL_SHOWTIME}!',
      cnr: 'Nažalost, gledaoci iz {COUNTRY} nemaju pravo da glasaju tokom Prvog polufinala kako je određeno u Alokacionom žrijebu. Molimo vas da nam se ponovo pridružite i glasate tokom Drugog polufinala koje počinje {SEMI2_SHOWTIME} i Velikog finala koje počinje {FINAL_SHOWTIME}!',
      nl: 'Helaas zijn kijkers uit {COUNTRY} niet stemgerechtigd tijdens de Eerste Halve Finale, zoals bepaald in de Allocatieloting. Sluit je alsjeblieft weer bij ons aan en stem tijdens de Tweede Halve Finale die begint {SEMI2_SHOWTIME} en de Grote Finale die begint {FINAL_SHOWTIME}!',
      no: 'Dessverre er seere fra {COUNTRY} ikke stemmeberettiget under den Første Semifinalen som bestemt i Fordelingstrekningen. Vennligst bli med oss igjen og stem under den Andre Semifinalen som starter {SEMI2_SHOWTIME} og den Store Finalen som starter {FINAL_SHOWTIME}!',
      pl: 'Niestety, widzowie z {COUNTRY} nie są uprawnieni do głosowania podczas Pierwszego Półfinału zgodnie z ustaleniami losowania przydziału. Prosimy dołączyć do nas ponownie i głosować podczas Drugiego Półfinału rozpoczynającego się {SEMI2_SHOWTIME} oraz Wielkiego Finału rozpoczynającego się {FINAL_SHOWTIME}!',
      pt: 'Infelizmente, os espectadores de {COUNTRY} não são elegíveis para votar durante a Primeira Semifinal, conforme determinado no Sorteio de Alocação. Por favor, junte-se a nós novamente e vote durante a Segunda Semifinal começando {SEMI2_SHOWTIME} e a Grande Final começando {FINAL_SHOWTIME}!',
      sr: 'Нажалост, гледаоци из {COUNTRY} немају право да гласају током Првог полуфинала како је одређено у Алокационом жребу. Молимо вас да нам се поново придружите и гласате током Другог полуфинала које почиње {SEMI2_SHOWTIME} и Великог финала које почиње {FINAL_SHOWTIME}!',
      sl: 'Na žalost gledalci iz {COUNTRY} niso upravičeni do glasovanja med Prvim polfinalom, kot je določeno v žrebu razporeditve. Prosimo, pridružite se nam ponovno in glasujte med Drugim polfinalom, ki se začne {SEMI2_SHOWTIME}, in Velikim finalom, ki se začne {FINAL_SHOWTIME}!',
      es: 'Desafortunadamente, los espectadores de {COUNTRY} no son elegibles para votar durante la Primera Semifinal según lo determinado en el Sorteo de Asignación. ¡Por favor, únete a nosotros de nuevo y vota durante la Segunda Semifinal que comienza {SEMI2_SHOWTIME} y la Gran Final que comienza {FINAL_SHOWTIME}!',
      sv: 'Tyvärr är tittare från {COUNTRY} inte röstberättigade under den Första Semifinalen enligt Fördelningsdragningen. Vänligen anslut dig till oss igen och rösta under den Andra Semifinalen som startar {SEMI2_SHOWTIME} och den Stora Finalen som startar {FINAL_SHOWTIME}!',
      uk: 'На жаль, глядачі з {COUNTRY} не мають права голосувати під час Першого півфіналу згідно з результатами жеребкування. Будь ласка, приєднуйтесь до нас знову та голосуйте під час Другого півфіналу, що розпочнеться {SEMI2_SHOWTIME}, та Гранд-фіналу, що розпочнеться {FINAL_SHOWTIME}!',
    },
  },
  notAllowedSemi2: {
    title: {
      en: '{ONBOARDING_TITLE_GENERIC}',
      sq: '{ONBOARDING_TITLE_GENERIC}',
      hy: '{ONBOARDING_TITLE_GENERIC}',
      az: '{ONBOARDING_TITLE_GENERIC}',
      hr: '{ONBOARDING_TITLE_GENERIC}',
      cs: '{ONBOARDING_TITLE_GENERIC}',
      da: '{ONBOARDING_TITLE_GENERIC}',
      et: '{ONBOARDING_TITLE_GENERIC}',
      fi: '{ONBOARDING_TITLE_GENERIC}',
      fr: '{ONBOARDING_TITLE_GENERIC}',
      ka: '{ONBOARDING_TITLE_GENERIC}',
      de: '{ONBOARDING_TITLE_GENERIC}',
      el: '{ONBOARDING_TITLE_GENERIC}',
      is: '{ONBOARDING_TITLE_GENERIC}',
      ga: '{ONBOARDING_TITLE_GENERIC}',
      he: '{ONBOARDING_TITLE_GENERIC}',
      it: '{ONBOARDING_TITLE_GENERIC}',
      lv: '{ONBOARDING_TITLE_GENERIC}',
      lt: '{ONBOARDING_TITLE_GENERIC}',
      lb: '{ONBOARDING_TITLE_GENERIC}',
      mt: '{ONBOARDING_TITLE_GENERIC}',
      cnr: '{ONBOARDING_TITLE_GENERIC}',
      nl: '{ONBOARDING_TITLE_GENERIC}',
      no: '{ONBOARDING_TITLE_GENERIC}',
      pl: '{ONBOARDING_TITLE_GENERIC}',
      pt: '{ONBOARDING_TITLE_GENERIC}',
      sr: '{ONBOARDING_TITLE_GENERIC}',
      sl: '{ONBOARDING_TITLE_GENERIC}',
      es: '{ONBOARDING_TITLE_GENERIC}',
      sv: '{ONBOARDING_TITLE_GENERIC}',
      uk: '{ONBOARDING_TITLE_GENERIC}',
    },
    description: {
      en: 'Unfortunately, viewers from {COUNTRY} are not eligible to vote during the Second Semi-Final as determined in the Allocation Draw. Please join us again during the Grand Final starting {FINAL_SHOWTIME}!',
      sq: 'Fatkeqësisht, shikuesit nga {COUNTRY} nuk janë të kualifikuar për të votuar gjatë Gjysmëfinales së Dytë siç është përcaktuar në Shortin e Ndarjes. Ju lutemi bashkohuni përsëri me ne gjatë Finales së Madhe duke filluar {FINAL_SHOWTIME}!',
      hy: 'Ցավոք, {COUNTRY}-ի հեռուստադիտողները իրավասու չեն քվեարկել Երկրորդ կիսաեզրափակչի ընթացքում՝ համաձայն Բաշխման վիճակահանության: Խնդրում ենք նորից միանալ մեզ Մեծ եզրափակչի ընթացքում՝ սկսած {FINAL_SHOWTIME}:',
      az: 'Təəssüf ki, {COUNTRY} ölkəsindən olan tamaşaçılar Bölüşdürmə Püşkatmasında müəyyən edildiyi kimi İkinci Yarımfinal zamanı səs verə bilməzlər. Lütfən, {FINAL_SHOWTIME} başlayan Böyük Final zamanı yenidən bizə qoşulun!',
      hr: 'Nažalost, gledatelji iz {COUNTRY} nemaju pravo glasati tijekom Drugog polufinala kako je određeno u Alokacijskom ždrijebu. Molimo vas da nam se ponovno pridružite tijekom Velikog finala koje počinje {FINAL_SHOWTIME}!',
      cs: 'Bohužel diváci z {COUNTRY} nemají právo hlasovat během druhého semifinále, jak bylo určeno ve výběru skupin. Připojte se k nám znovu během velkého finále, které začíná {FINAL_SHOWTIME}!',
      da: 'Desværre er seere fra {COUNTRY} ikke berettigede til at stemme under den Anden Semifinale som bestemt ved lodtrækningen. Vær venlig at deltage igen under den Store Finale, der starter {FINAL_SHOWTIME}!',
      et: 'Kahjuks ei ole {COUNTRY} vaatajatel loosi alusel õigust hääletada Teises poolfinaalis. Palun liituge meiega uuesti Suure Finaali ajal alates {FINAL_SHOWTIME}!',
      fi: 'Valitettavasti katsojat maasta {COUNTRY} eivät ole oikeutettuja äänestämään Toisessa semifinaalissa Allokaatioarvonnan mukaisesti. Liitythän seuraamme uudelleen Suuressa finaalissa alkaen {FINAL_SHOWTIME}!',
      fr: 'Malheureusement, les téléspectateurs de {COUNTRY} ne sont pas éligibles pour voter lors de la Deuxième Demi-finale, comme déterminé lors du Tirage au sort. Merci de nous rejoindre à nouveau lors de la Grande Finale à partir de {FINAL_SHOWTIME} !',
      ka: 'სამწუხაროდ, {COUNTRY}-ის მაყურებლებს არ აქვთ უფლება ხმის მიცემის მეორე ნახევარფინალში, განაწილების წილისყრის მიხედვით. გთხოვთ, შემოგვიერთდეთ კვლავ გრანდ ფინალის დროს, რომელიც იწყება {FINAL_SHOWTIME}!',
      de: 'Leider sind Zuschauer:innen aus {COUNTRY} nicht berechtigt, während des Zweiten Halbfinales abzustimmen, wie im Allocation Draw bestimmt wurde. Bitte schließen Sie sich uns wieder während des Großen Finales ab {FINAL_SHOWTIME} an!',
      el: 'Δυστυχώς, οι τηλεθεατές από την {COUNTRY} δεν έχουν δικαίωμα να ψηφίσουν κατά τον Δεύτερο Ημιτελικό όπως καθορίστηκε στην Κλήρωση Κατανομής. Παρακαλούμε ελάτε ξανά μαζί μας κατά τη διάρκεια του Μεγάλου Τελικού που ξεκινά {FINAL_SHOWTIME}!',
      is: 'Því miður eru áhorfendur frá {COUNTRY} ekki gjaldgengir til að kjósa í Seinni undanúrslitum eins og ákveðið var í úthlutunardrættinum. Vinsamlegast vertu með okkur aftur í Stóru úrslitunum sem hefjast {FINAL_SHOWTIME}!',
      ga: 'Ar an drochuair, níl lucht féachana ó {COUNTRY} i dteideal vótáil le linn an Dara Cluiche Leathcheannais mar a cinneadh sa Tarraingt Leithdháilte. Bí linn arís le linn an Grand Final ag tosú {FINAL_SHOWTIME}!',
      he: 'לצערנו, צופים מ{COUNTRY} אינם רשאים להצביע במהלך חצי הגמר השני כפי שנקבע בהגרלת החלוקה. אנא הצטרפו אלינו שוב במהלך הגמר הגדול שיתחיל {FINAL_SHOWTIME}!',
      it: 'Purtroppo, gli spettatori da {COUNTRY} non sono idonei a votare durante la Seconda Semifinale come determinato nel Sorteggio di Allocazione. Per favore, unisciti a noi di nuovo durante la Grand Finale a partire da {FINAL_SHOWTIME}!',
      lv: 'Diemžēl skatītāji no {COUNTRY} nav tiesīgi balsot Otrajā pusfinālā, kā noteikts Sadalījuma izlozē. Lūdzu, pievienojieties mums atkal Lielajā finālā, kas sākas {FINAL_SHOWTIME}!',
      lt: 'Deja, žiūrovai iš {COUNTRY} negali balsuoti Antrajame pusfinalyje, kaip nustatyta Paskirstymo burtų traukimo metu. Prašome prisijungti prie mūsų vėl Didžiajame finale, pradedant {FINAL_SHOWTIME}!',
      lb: 'Leider sinn Zuschauer aus {COUNTRY} net berechtegt, während der Zweeter Halleffinall ofzestëmmen, wéi et am Allocation Draw bestëmmt gouf. Maacht w.e.g. erëm mat während der Grousser Finall of {FINAL_SHOWTIME}!',
      mt: 'Sfortunatament, it-telespettaturi minn {COUNTRY} mhumiex eliġibbli biex jivvutaw matul it-Tieni Semi-Finali kif determinat fit-Telfa tal-Allokazzjoni. Jekk jogħġbok ingħaqad magħna mill-ġdid matul il-Finali l-Kbira li tibda {FINAL_SHOWTIME}!',
      cnr: 'Nažalost, gledaoci iz {COUNTRY} nemaju pravo da glasaju tokom Drugog polufinala kako je određeno u Alokacionom žrijebu. Molimo vas da nam se ponovo pridružite tokom Velikog finala koje počinje {FINAL_SHOWTIME}!',
      nl: 'Helaas zijn kijkers uit {COUNTRY} niet stemgerechtigd tijdens de Tweede Halve Finale, zoals bepaald in de Allocatieloting. Sluit je alsjeblieft weer bij ons aan tijdens de Grote Finale die begint {FINAL_SHOWTIME}!',
      no: 'Dessverre er seere fra {COUNTRY} ikke stemmeberettiget under den Andre Semifinalen som bestemt i Fordelingstrekningen. Vennligst bli med oss igjen under den Store Finalen som starter {FINAL_SHOWTIME}!',
      pl: 'Niestety, widzowie z {COUNTRY} nie są uprawnieni do głosowania podczas Drugiego Półfinału zgodnie z ustaleniami losowania przydziału. Prosimy dołączyć do nas ponownie podczas Wielkiego Finału rozpoczynającego się {FINAL_SHOWTIME}!',
      pt: 'Infelizmente, os espectadores de {COUNTRY} não são elegíveis para votar durante a Segunda Semifinal, conforme determinado no Sorteio de Alocação. Por favor, junte-se a nós novamente durante a Grande Final começando {FINAL_SHOWTIME}!',
      sr: 'Нажалост, гледаоци из {COUNTRY} немају право да гласају током Другог полуфинала како је одређено у Алокационом жребу. Молимо вас да нам се поново придружите током Великог финала које почиње {FINAL_SHOWTIME}!',
      sl: 'Na žalost gledalci iz {COUNTRY} niso upravičeni do glasovanja med Drugim polfinalom, kot je določeno v žrebu razporeditve. Prosimo, pridružite se nam ponovno med Velikim finalom, ki se začne {FINAL_SHOWTIME}!',
      es: 'Desafortunadamente, los espectadores de {COUNTRY} no son elegibles para votar durante la Segunda Semifinal según lo determinado en el Sorteo de Asignación. ¡Por favor, únete a nosotros de nuevo durante la Gran Final que comienza {FINAL_SHOWTIME}!',
      sv: 'Tyvärr är tittare från {COUNTRY} inte röstberättigade under den Andra Semifinalen enligt Fördelningsdragningen. Vänligen anslut dig till oss igen under den Stora Finalen som startar {FINAL_SHOWTIME}!',
      uk: 'На жаль, глядачі з {COUNTRY} не мають права голосувати під час Другого півфіналу згідно з результатами жеребкування. Будь ласка, приєднуйтесь до нас знову під час Гранд-фіналу, що розпочнеться {FINAL_SHOWTIME}!',
    },
  },
  nonVoting: {
    title: {
      en: '{ONBOARDING_TITLE_GENERIC}',
      sq: '{ONBOARDING_TITLE_GENERIC}',
      hy: '{ONBOARDING_TITLE_GENERIC}',
      az: '{ONBOARDING_TITLE_GENERIC}',
      hr: '{ONBOARDING_TITLE_GENERIC}',
      cs: '{ONBOARDING_TITLE_GENERIC}',
      da: '{ONBOARDING_TITLE_GENERIC}',
      et: '{ONBOARDING_TITLE_GENERIC}',
      fi: '{ONBOARDING_TITLE_GENERIC}',
      fr: '{ONBOARDING_TITLE_GENERIC}',
      ka: '{ONBOARDING_TITLE_GENERIC}',
      de: '{ONBOARDING_TITLE_GENERIC}',
      el: '{ONBOARDING_TITLE_GENERIC}',
      is: '{ONBOARDING_TITLE_GENERIC}',
      ga: '{ONBOARDING_TITLE_GENERIC}',
      he: '{ONBOARDING_TITLE_GENERIC}',
      it: '{ONBOARDING_TITLE_GENERIC}',
      lv: '{ONBOARDING_TITLE_GENERIC}',
      lt: '{ONBOARDING_TITLE_GENERIC}',
      lb: '{ONBOARDING_TITLE_GENERIC}',
      mt: '{ONBOARDING_TITLE_GENERIC}',
      cnr: '{ONBOARDING_TITLE_GENERIC}',
      nl: '{ONBOARDING_TITLE_GENERIC}',
      no: '{ONBOARDING_TITLE_GENERIC}',
      pl: '{ONBOARDING_TITLE_GENERIC}',
      pt: '{ONBOARDING_TITLE_GENERIC}',
      sr: '{ONBOARDING_TITLE_GENERIC}',
      sl: '{ONBOARDING_TITLE_GENERIC}',
      es: '{ONBOARDING_TITLE_GENERIC}',
      sv: '{ONBOARDING_TITLE_GENERIC}',
      uk: '{ONBOARDING_TITLE_GENERIC}',
    },
    description: {
      // en: 'Unfortunately, we do not support votes coming from payment cards issued in {COUNTRY}. If you have a payment card issued in Italy, you may be able to participate on behalf of Italy. If this applies to you, please {SELECT_ITALY:click here}.',
      // it: "Purtroppo, non supportiamo i voti provenienti da carte di pagamento emesse a {COUNTRY}. Se possiedi una carta di pagamento emessa in Italia, potresti essere in grado di partecipare per conto dell'Italia. Se questo si applica a te, per favore {SELECT_ITALY:clicca qui}.",
      en: 'Unfortunately, we do not support votes coming from payment cards issued in {COUNTRY}. If you have a payment card issued elsewhere, please select the corresponding voting region.',
      sq: 'Fatkeqësisht, ne nuk mbështesim votat që vijnë nga kartat e pagesave të lëshuara në {COUNTRY}. Nëse keni një kartë pagese të lëshuar diku tjetër, ju lutemi zgjidhni rajonin përkatës të votimit.',
      hy: 'Ցավոք, մենք չենք սպասարկում {COUNTRY}-ում թողարկված վճարային քարտերից եկող ձայները: Եթե ունեք այլ վայրում թողարկված վճարային քարտ, խնդրում ենք ընտրել համապատասխան քվեարկության տարածաշրջանը:',
      az: 'Təəssüf ki, biz {COUNTRY} ölkəsində verilmiş ödəniş kartlarından gələn səsləri dəstəkləmirik. Əgər başqa yerdə verilmiş ödəniş kartınız varsa, lütfən müvafiq səsvermə bölgəsini seçin.',
      hr: 'Nažalost, ne podržavamo glasove koji dolaze s platnih kartica izdanih u {COUNTRY}. Ako imate platnu karticu izdanu drugdje, molimo odaberite odgovarajuću regiju za glasanje.',
      cs: 'Bohužel nepodporujeme hlasy pocházející z platebních karet vydaných v {COUNTRY}. Pokud máte platební kartu vydanou jinde, vyberte prosím odpovídající hlasovací region.',
      da: 'Desværre understøtter vi ikke stemmer fra betalingskort udstedt i {COUNTRY}. Hvis du har et betalingskort udstedt et andet sted, bedes du vælge den tilsvarende stemme region.',
      et: 'Kahjuks me ei toeta hääli, mis tulevad {COUNTRY}s väljastatud maksekaartidelt. Kui teil on mujal väljastatud maksekaart, valige palun vastav hääletuspiirkond.',
      fi: 'Valitettavasti emme tue ääniä, jotka tulevat maassa {COUNTRY} myönnetyiltä maksukorteilta. Jos sinulla on muualla myönnetty maksukortti, valitse vastaava äänestysalue.',
      fr: 'Malheureusement, nous ne prenons pas en charge les votes provenant de cartes de paiement émises en {COUNTRY}. Si vous possédez une carte de paiement émise ailleurs, veuillez sélectionner la région de vote correspondante.',
      ka: 'სამწუხაროდ, ჩვენ არ ვუჭერთ მხარს {COUNTRY}-ში გაცემული საგადახდო ბარათებიდან მოსულ ხმებს. თუ თქვენ გაქვთ სხვაგან გაცემული საგადახდო ბარათი, გთხოვთ, აირჩიოთ შესაბამისი ხმის მიცემის რეგიონი.',
      de: 'Leider unterstützen wir keine Stimmen von Zahlungskarten, die in {COUNTRY} ausgestellt wurden. Wenn Sie eine Zahlungskarte besitzen, die anderswo ausgestellt wurde, wählen Sie bitte die entsprechende Abstimmungsregion aus.',
      el: 'Δυστυχώς, δεν υποστηρίζουμε ψήφους που προέρχονται από κάρτες πληρωμής που έχουν εκδοθεί στην {COUNTRY}. Εάν διαθέτετε κάρτα πληρωμής που έχει εκδοθεί αλλού, παρακαλούμε επιλέξτε την αντίστοιχη περιοχή ψηφοφορίας.',
      is: 'Því miður styðjum við ekki atkvæði sem koma frá greiðslukortum gefnum út í {COUNTRY}. Ef þú ert með greiðslukort gefið út annars staðar, vinsamlegast veldu samsvarandi kosningasvæði.',
      ga: 'Ar an drochuair, ní thacaímid le vótaí ó chártaí íocaíochta a eisíodh i {COUNTRY}. Má tá cárta íocaíochta agat a eisíodh in áit eile, roghnaigh an réigiún vótála comhfhreagrach le do thoil.',
      he: 'לצערנו, איננו תומכים בהצבעות המגיעות מכרטיסי תשלום שהונפקו ב{COUNTRY}. אם יש ברשותכם כרטיס תשלום שהונפק במקום אחר, אנא בחרו את אזור ההצבעה המתאים.',
      it: 'Purtroppo, non supportiamo i voti provenienti da carte di pagamento emesse in {COUNTRY}. Se possiedi una carta di pagamento emessa altrove, seleziona la regione di voto corrispondente.',
      lv: 'Diemžēl mēs neatbalstām balsis no maksājumu kartēm, kas izdotas {COUNTRY}. Ja jums ir maksājumu karte, kas izdota citur, lūdzu, izvēlieties atbilstošo balsošanas reģionu.',
      lt: 'Deja, nepalaikome balsų iš mokėjimo kortelių, išduotų {COUNTRY}. Jei turite kitur išduotą mokėjimo kortelę, pasirinkite atitinkamą balsavimo regioną.',
      lb: 'Leider ënnerstëtze mir keng Stëmme vu Bezuelkaarten, déi a(n) {COUNTRY} ausgestallt goufen. Wann Dir eng Bezuelkaart hutt, déi soss anzwousch ausgestallt gouf, wielt w.e.g. déi entspriechend Ofstëmmungsregioun aus.',
      mt: "Sfortunatament, ma nappoġġjawx voti li jiġu minn karti tal-ħlas maħruġa f'{COUNTRY}. Jekk għandek karta tal-ħlas maħruġa x'imkien ieħor, jekk jogħġbok agħżel ir-reġjun tal-votazzjoni korrispondenti.",
      cnr: 'Nažalost, ne podržavamo glasove koji dolaze sa platnih kartica izdatih u {COUNTRY}. Ako imate platnu karticu izdatu negdje drugo, molimo odaberite odgovarajuću regiju za glasanje.',
      nl: 'Helaas ondersteunen we geen stemmen afkomstig van betaalkaarten die zijn uitgegeven in {COUNTRY}. Als u een betaalkaart heeft die elders is uitgegeven, selecteer dan de overeenkomstige stemregio.',
      no: 'Dessverre støtter vi ikke stemmer som kommer fra betalingskort utstedt i {COUNTRY}. Hvis du har et betalingskort utstedt et annet sted, vennligst velg den tilsvarende stemmeregionen.',
      pl: 'Niestety, nie obsługujemy głosów pochodzących z kart płatniczych wydanych w {COUNTRY}. Jeśli posiadasz kartę płatniczą wydaną gdzie indziej, wybierz odpowiedni region głosowania.',
      pt: 'Infelizmente, não apoiamos votos provenientes de cartões de pagamento emitidos em {COUNTRY}. Se tiver um cartão de pagamento emitido noutro local, selecione a região de votação correspondente.',
      sr: 'Нажалост, не подржавамо гласове који долазе са платних картица издатих у {COUNTRY}. Ако имате платну картицу издату на другом месту, молимо одаберите одговарајућу регију за гласање.',
      sl: 'Žal ne podpiramo glasov s plačilnih kartic, izdanih v državi {COUNTRY}. Če imate plačilno kartico, izdano drugje, izberite ustrezno regijo za glasovanje.',
      es: 'Lamentablemente, no admitimos votos procedentes de tarjetas de pago emitidas en {COUNTRY}. Si tienes una tarjeta de pago emitida en otro lugar, selecciona la región de votación correspondiente.',
      sv: 'Tyvärr stöder vi inte röster från betalkort utfärdade i {COUNTRY}. Om du har ett betalkort utfärdat någon annanstans, vänligen välj motsvarande röstningsregion.',
      uk: 'На жаль, ми не підтримуємо голоси, що надходять з платіжних карток, виданих у {COUNTRY}. Якщо у вас є платіжна картка, видана в іншому місці, будь ласка, виберіть відповідний регіон для голосування.',
    },
  },
  overseasParent: {
    title: {
      en: '{ONBOARDING_TITLE_OVERSEAS}',
      sq: '{ONBOARDING_TITLE_OVERSEAS}',
      hy: '{ONBOARDING_TITLE_OVERSEAS}',
      az: '{ONBOARDING_TITLE_OVERSEAS}',
      hr: '{ONBOARDING_TITLE_OVERSEAS}',
      cs: '{ONBOARDING_TITLE_OVERSEAS}',
      da: '{ONBOARDING_TITLE_OVERSEAS}',
      et: '{ONBOARDING_TITLE_OVERSEAS}',
      fi: '{ONBOARDING_TITLE_OVERSEAS}',
      fr: '{ONBOARDING_TITLE_OVERSEAS}',
      ka: '{ONBOARDING_TITLE_OVERSEAS}',
      de: '{ONBOARDING_TITLE_OVERSEAS}',
      el: '{ONBOARDING_TITLE_OVERSEAS}',
      is: '{ONBOARDING_TITLE_OVERSEAS}',
      ga: '{ONBOARDING_TITLE_OVERSEAS}',
      he: '{ONBOARDING_TITLE_OVERSEAS}',
      it: '{ONBOARDING_TITLE_OVERSEAS}',
      lv: '{ONBOARDING_TITLE_OVERSEAS}',
      lt: '{ONBOARDING_TITLE_OVERSEAS}',
      lb: '{ONBOARDING_TITLE_OVERSEAS}',
      mt: '{ONBOARDING_TITLE_OVERSEAS}',
      cnr: '{ONBOARDING_TITLE_OVERSEAS}',
      nl: '{ONBOARDING_TITLE_OVERSEAS}',
      no: '{ONBOARDING_TITLE_OVERSEAS}',
      pl: '{ONBOARDING_TITLE_OVERSEAS}',
      pt: '{ONBOARDING_TITLE_OVERSEAS}',
      sr: '{ONBOARDING_TITLE_OVERSEAS}',
      sl: '{ONBOARDING_TITLE_OVERSEAS}',
      es: '{ONBOARDING_TITLE_OVERSEAS}',
      sv: '{ONBOARDING_TITLE_OVERSEAS}',
      uk: '{ONBOARDING_TITLE_OVERSEAS}',
    },
    description: {
      en: 'In order to cast votes on behalf of {COUNTRY}, you will need a SIM card with a phone number from {COUNTRY} ({DIAL}).',
      sq: "Për të hedhur vota në emër të {COUNTRY}, do t'ju duhet një kartë SIM me një numër telefoni nga {COUNTRY} ({DIAL}).",
      hy: '{COUNTRY}-ի անունից քվեարկելու համար ձեզ անհրաժեշտ կլինի SIM քարտ՝ {COUNTRY}-ի հեռախոսահամարով ({DIAL})։',
      az: '{COUNTRY} adından səs vermək üçün sizə {COUNTRY} ({DIAL}) telefon nömrəsi olan SİM kart lazım olacaq.',
      hr: 'Kako biste glasali u ime {COUNTRY}, trebat će vam SIM kartica s telefonskim brojem iz {COUNTRY} ({DIAL}).',
      cs: 'Pro hlasování jménem {COUNTRY} potřebujete SIM kartu s telefonním číslem z {COUNTRY} ({DIAL}).',
      da: 'For at afgive stemmer på vegne af {COUNTRY}, skal du bruge et SIM-kort med et telefonnummer fra {COUNTRY} ({DIAL}).',
      et: 'Et hääletada {COUNTRY} nimel, on vaja SIM-kaarti telefoninumbriga {COUNTRY}-st ({DIAL}).',
      fi: 'Voidaksesi äänestää maan {COUNTRY} puolesta tarvitset SIM-kortin, jossa on puhelinnumero maasta {COUNTRY} ({DIAL}).',
      fr: "Pour voter au nom de {COUNTRY}, vous aurez besoin d'une carte SIM avec un numéro de téléphone de {COUNTRY} ({DIAL}).",
      ka: '{COUNTRY}-ის სახელით ხმის მისაცემად დაგჭირდებათ SIM ბარათი {COUNTRY}-ის ({DIAL}) ტელეფონის ნომრით.',
      de: 'Um Stimmen im Namen von {COUNTRY} abzugeben, benötigen Sie eine SIM-Karte mit einer Telefonnummer aus {COUNTRY} ({DIAL}).',
      el: 'Για να ψηφίσετε εκ μέρους της {COUNTRY}, θα χρειαστείτε μια κάρτα SIM με τηλεφωνικό αριθμό από την {COUNTRY} ({DIAL}).',
      is: 'Til að greiða atkvæði fyrir hönd {COUNTRY} þarftu SIM-kort með símanúmeri frá {COUNTRY} ({DIAL}).',
      ga: 'Chun vótaí a chaitheamh thar ceann {COUNTRY}, beidh cárta SIM uait le huimhir theileafóin ó {COUNTRY} ({DIAL}).',
      he: 'כדי להצביע בשם {COUNTRY}, תזדקקו לכרטיס SIM עם מספר טלפון מ{COUNTRY} ({DIAL}).',
      it: 'Per votare per conto di {COUNTRY}, avrai bisogno di una scheda SIM con un numero di telefono da {COUNTRY} ({DIAL}).',
      lv: 'Lai balsotu {COUNTRY} vārdā, jums būs nepieciešama SIM karte ar {COUNTRY} tālruņa numuru ({DIAL}).',
      lt: 'Norint balsuoti {COUNTRY} vardu, jums reikės SIM kortelės su telefono numeriu iš {COUNTRY} ({DIAL}).',
      lb: 'Fir am Numm vu(n) {COUNTRY} ofzestëmmen, braucht Dir eng SIM-Kaart mat enger Telefonsnummer aus {COUNTRY} ({DIAL}).',
      mt: "Sabiex titfa' voti f'isem {COUNTRY}, ser ikollok bżonn SIM card b'numru tat-telefon minn {COUNTRY} ({DIAL}).",
      cnr: 'Da biste glasali u ime {COUNTRY}, biće vam potrebna SIM kartica sa telefonskim brojem iz {COUNTRY} ({DIAL}).',
      nl: 'Om namens {COUNTRY} te stemmen, heb je een SIM-kaart nodig met een telefoonnummer uit {COUNTRY} ({DIAL}).',
      no: 'For å avgi stemmer på vegne av {COUNTRY}, trenger du et SIM-kort med et telefonnummer fra {COUNTRY} ({DIAL}).',
      pl: 'Aby oddać głosy w imieniu {COUNTRY}, potrzebujesz karty SIM z numerem telefonu z {COUNTRY} ({DIAL}).',
      pt: 'Para votar em nome de {COUNTRY}, precisará de um cartão SIM com um número de telefone de {COUNTRY} ({DIAL}).',
      sr: 'Да бисте гласали у име {COUNTRY}, биће вам потребна СИМ картица са телефонским бројем из {COUNTRY} ({DIAL}).',
      sl: 'Za glasovanje v imenu države {COUNTRY} potrebujete kartico SIM s telefonsko številko iz države {COUNTRY} ({DIAL}).',
      es: 'Para votar en nombre de {COUNTRY}, necesitarás una tarjeta SIM con un número de teléfono de {COUNTRY} ({DIAL}).',
      sv: 'För att rösta för {COUNTRY} behöver du ett SIM-kort med ett telefonnummer från {COUNTRY} ({DIAL}).',
      uk: 'Щоб проголосувати від імені {COUNTRY}, вам знадобиться SIM-карта з телефонним номером {COUNTRY} ({DIAL}).',
    },
  },
  overseasPhone: {
    title: {
      en: '{ONBOARDING_TITLE_OVERSEAS}',
      sq: '{ONBOARDING_TITLE_OVERSEAS}',
      hy: '{ONBOARDING_TITLE_OVERSEAS}',
      az: '{ONBOARDING_TITLE_OVERSEAS}',
      hr: '{ONBOARDING_TITLE_OVERSEAS}',
      cs: '{ONBOARDING_TITLE_OVERSEAS}',
      da: '{ONBOARDING_TITLE_OVERSEAS}',
      et: '{ONBOARDING_TITLE_OVERSEAS}',
      fi: '{ONBOARDING_TITLE_OVERSEAS}',
      fr: '{ONBOARDING_TITLE_OVERSEAS}',
      ka: '{ONBOARDING_TITLE_OVERSEAS}',
      de: '{ONBOARDING_TITLE_OVERSEAS}',
      el: '{ONBOARDING_TITLE_OVERSEAS}',
      is: '{ONBOARDING_TITLE_OVERSEAS}',
      ga: '{ONBOARDING_TITLE_OVERSEAS}',
      he: '{ONBOARDING_TITLE_OVERSEAS}',
      it: '{ONBOARDING_TITLE_OVERSEAS}',
      lv: '{ONBOARDING_TITLE_OVERSEAS}',
      lt: '{ONBOARDING_TITLE_OVERSEAS}',
      lb: '{ONBOARDING_TITLE_OVERSEAS}',
      mt: '{ONBOARDING_TITLE_OVERSEAS}',
      cnr: '{ONBOARDING_TITLE_OVERSEAS}',
      nl: '{ONBOARDING_TITLE_OVERSEAS}',
      no: '{ONBOARDING_TITLE_OVERSEAS}',
      pl: '{ONBOARDING_TITLE_OVERSEAS}',
      pt: '{ONBOARDING_TITLE_OVERSEAS}',
      sr: '{ONBOARDING_TITLE_OVERSEAS}',
      sl: '{ONBOARDING_TITLE_OVERSEAS}',
      es: '{ONBOARDING_TITLE_OVERSEAS}',
      sv: '{ONBOARDING_TITLE_OVERSEAS}',
      uk: '{ONBOARDING_TITLE_OVERSEAS}',
    },
    description: {
      en: 'In order to cast votes on behalf of {COUNTRY}, you will need a SIM card with a phone number from {OVERSEAS} ({OVERSEAS_DIAL}) or {COUNTRY} ({DIAL}).',
      sq: "Për të hedhur vota në emër të {COUNTRY}, do t'ju duhet një kartë SIM me një numër telefoni nga {OVERSEAS} ({OVERSEAS_DIAL}) ose {COUNTRY} ({DIAL}).",
      hy: '{COUNTRY}-ի անունից քվեարկելու համար ձեզ անհրաժեշտ կլինի SIM քարտ՝ {OVERSEAS}-ի ({OVERSEAS_DIAL}) կամ {COUNTRY}-ի ({DIAL}) հեռախոսահամարով:',
      az: '{COUNTRY} adından səs vermək üçün sizə {OVERSEAS} ({OVERSEAS_DIAL}) və ya {COUNTRY} ({DIAL}) telefon nömrəsi olan SİM kart lazım olacaq.',
      hr: 'Kako biste glasali u ime {COUNTRY}, trebat će vam SIM kartica s telefonskim brojem iz {OVERSEAS} ({OVERSEAS_DIAL}) ili {COUNTRY} ({DIAL}).',
      cs: 'Pro hlasování za {COUNTRY} potřebujete SIM kartu s telefonním číslem z {OVERSEAS} ({OVERSEAS_DIAL}) nebo z {COUNTRY} ({DIAL}).',
      da: 'For at afgive stemmer på vegne af {COUNTRY}, skal du bruge et SIM-kort med et telefonnummer fra {OVERSEAS} ({OVERSEAS_DIAL}) eller {COUNTRY} ({DIAL}).',
      et: 'Et hääletada {COUNTRY} nimel, on vaja SIM-kaarti telefoninumbriga {OVERSEAS}-st ({OVERSEAS_DIAL}) või {COUNTRY}-st ({DIAL}).',
      fi: 'Voidaksesi äänestää maan {COUNTRY} puolesta tarvitset SIM-kortin, jossa on puhelinnumero maasta {OVERSEAS} ({OVERSEAS_DIAL}) tai {COUNTRY} ({DIAL}).',
      fr: "Pour voter au nom de {COUNTRY}, vous aurez besoin d'une carte SIM avec un numéro de téléphone de {OVERSEAS} ({OVERSEAS_DIAL}) ou de {COUNTRY} ({DIAL}).",
      ka: '{COUNTRY}-ის სახელით ხმის მისაცემად დაგჭირდებათ SIM ბარათი {OVERSEAS}-ის ({OVERSEAS_DIAL}) ან {COUNTRY}-ის ({DIAL}) ტელეფონის ნომრით.',
      de: 'Um Stimmen im Namen von {COUNTRY} abzugeben, benötigen Sie eine SIM-Karte mit einer Telefonnummer aus {OVERSEAS} ({OVERSEAS_DIAL}) oder {COUNTRY} ({DIAL}).',
      el: 'Για να ψηφίσετε εκ μέρους της {COUNTRY}, θα χρειαστείτε μια κάρτα SIM με αριθμό τηλεφώνου από {OVERSEAS} ({OVERSEAS_DIAL}) ή {COUNTRY} ({DIAL}).',
      is: 'Til að greiða atkvæði fyrir hönd {COUNTRY} þarftu SIM-kort með símanúmeri frá {OVERSEAS} ({OVERSEAS_DIAL}) eða {COUNTRY} ({DIAL}).',
      ga: 'Chun vótaí a chaitheamh thar ceann {COUNTRY}, beidh cárta SIM uait le huimhir theileafóin ó {OVERSEAS} ({OVERSEAS_DIAL}) nó ó {COUNTRY} ({DIAL}).',
      he: 'כדי להצביע בשם {COUNTRY}, תזדקקו לכרטיס SIM עם מספר טלפון מ{OVERSEAS} ({OVERSEAS_DIAL}) או מ{COUNTRY} ({DIAL}).',
      it: 'Per votare per conto di {COUNTRY}, avrai bisogno di una scheda SIM con un numero di telefono da {OVERSEAS} ({OVERSEAS_DIAL}) o da {COUNTRY} ({DIAL}).',
      lv: 'Lai balsotu {COUNTRY} vārdā, jums būs nepieciešama SIM karte ar tālruņa numuru no {OVERSEAS} ({OVERSEAS_DIAL}) vai {COUNTRY} ({DIAL}).',
      lt: 'Norint balsuoti {COUNTRY} vardu, jums reikės SIM kortelės su telefono numeriu iš {OVERSEAS} ({OVERSEAS_DIAL}) arba {COUNTRY} ({DIAL}).',
      lb: 'Fir am Numm vu(n) {COUNTRY} ofzestëmmen, braucht Dir eng SIM-Kaart mat enger Telefonsnummer aus {OVERSEAS} ({OVERSEAS_DIAL}) oder aus {COUNTRY} ({DIAL}).',
      mt: "Sabiex titfa' voti f'isem {COUNTRY}, ser ikollok bżonn SIM card b'numru tat-telefon minn {OVERSEAS} ({OVERSEAS_DIAL}) jew {COUNTRY} ({DIAL}).",
      cnr: 'Da biste glasali u ime {COUNTRY}, biće vam potrebna SIM kartica sa telefonskim brojem iz {OVERSEAS} ({OVERSEAS_DIAL}) ili {COUNTRY} ({DIAL}).',
      nl: 'Om namens {COUNTRY} te stemmen, heb je een SIM-kaart nodig met een telefoonnummer uit {OVERSEAS} ({OVERSEAS_DIAL}) of {COUNTRY} ({DIAL}).',
      no: 'For å avgi stemmer på vegne av {COUNTRY}, trenger du et SIM-kort med et telefonnummer fra {OVERSEAS} ({OVERSEAS_DIAL}) eller {COUNTRY} ({DIAL}).',
      pl: 'Aby oddać głosy w imieniu {COUNTRY}, potrzebujesz karty SIM z numerem telefonu z {OVERSEAS} ({OVERSEAS_DIAL}) lub {COUNTRY} ({DIAL}).',
      pt: 'Para votar em nome de {COUNTRY}, precisará de um cartão SIM com um número de telefone de {OVERSEAS} ({OVERSEAS_DIAL}) ou {COUNTRY} ({DIAL}).',
      sr: 'Да бисте гласали у име {COUNTRY}, биће вам потребна СИМ картица са телефонским бројем из {OVERSEAS} ({OVERSEAS_DIAL}) или {COUNTRY} ({DIAL}).',
      sl: 'Za glasovanje v imenu države {COUNTRY} potrebujete kartico SIM s telefonsko številko iz države {OVERSEAS} ({OVERSEAS_DIAL}) ali {COUNTRY} ({DIAL}).',
      es: 'Para votar en nombre de {COUNTRY}, necesitarás una tarjeta SIM con un número de teléfono de {OVERSEAS} ({OVERSEAS_DIAL}) o de {COUNTRY} ({DIAL}).',
      sv: 'För att rösta för {COUNTRY} behöver du ett SIM-kort med ett telefonnummer från {OVERSEAS} ({OVERSEAS_DIAL}) eller {COUNTRY} ({DIAL}).',
      uk: 'Щоб проголосувати від імені {COUNTRY}, вам знадобиться SIM-карта з телефонним номером {OVERSEAS} ({OVERSEAS_DIAL}) або {COUNTRY} ({DIAL}).',
    },
  },
  overseasOnline: {
    title: {
      en: '{ONBOARDING_TITLE_OVERSEAS}',
      sq: '{ONBOARDING_TITLE_OVERSEAS}',
      hy: '{ONBOARDING_TITLE_OVERSEAS}',
      az: '{ONBOARDING_TITLE_OVERSEAS}',
      hr: '{ONBOARDING_TITLE_OVERSEAS}',
      cs: '{ONBOARDING_TITLE_OVERSEAS}',
      da: '{ONBOARDING_TITLE_OVERSEAS}',
      et: '{ONBOARDING_TITLE_OVERSEAS}',
      fi: '{ONBOARDING_TITLE_OVERSEAS}',
      fr: '{ONBOARDING_TITLE_OVERSEAS}',
      ka: '{ONBOARDING_TITLE_OVERSEAS}',
      de: '{ONBOARDING_TITLE_OVERSEAS}',
      el: '{ONBOARDING_TITLE_OVERSEAS}',
      is: '{ONBOARDING_TITLE_OVERSEAS}',
      ga: '{ONBOARDING_TITLE_OVERSEAS}',
      he: '{ONBOARDING_TITLE_OVERSEAS}',
      it: '{ONBOARDING_TITLE_OVERSEAS}',
      lv: '{ONBOARDING_TITLE_OVERSEAS}',
      lt: '{ONBOARDING_TITLE_OVERSEAS}',
      lb: '{ONBOARDING_TITLE_OVERSEAS}',
      mt: '{ONBOARDING_TITLE_OVERSEAS}',
      cnr: '{ONBOARDING_TITLE_OVERSEAS}',
      nl: '{ONBOARDING_TITLE_OVERSEAS}',
      no: '{ONBOARDING_TITLE_OVERSEAS}',
      pl: '{ONBOARDING_TITLE_OVERSEAS}',
      pt: '{ONBOARDING_TITLE_OVERSEAS}',
      sr: '{ONBOARDING_TITLE_OVERSEAS}',
      sl: '{ONBOARDING_TITLE_OVERSEAS}',
      es: '{ONBOARDING_TITLE_OVERSEAS}',
      sv: '{ONBOARDING_TITLE_OVERSEAS}',
      uk: '{ONBOARDING_TITLE_OVERSEAS}',
    },
    description: {
      en: 'In order to cast votes on behalf of {COUNTRY}, you will need a payment card that was issued in {OVERSEAS} or {COUNTRY}.',
      sq: "Për të hedhur vota në emër të {COUNTRY}, do t'ju duhet një kartë pagese që është lëshuar në {OVERSEAS} ose {COUNTRY}.",
      hy: '{COUNTRY}-ի անունից քվեարկելու համար ձեզ անհրաժեշտ կլինի վճարային քարտ, որը թողարկվել է {OVERSEAS}-ում կամ {COUNTRY}-ում:',
      az: '{COUNTRY} adından səs vermək üçün sizə {OVERSEAS} və ya {COUNTRY}-də verilmiş ödəniş kartı lazım olacaq.',
      hr: 'Kako biste glasali u ime {COUNTRY}, trebat će vam platna kartica izdana u {OVERSEAS} ili {COUNTRY}.',
      cs: 'Pro hlasování za {COUNTRY} potřebujete platební kartu vydanou v {OVERSEAS} nebo v {COUNTRY}.',
      da: 'For at afgive stemmer på vegne af {COUNTRY}, skal du bruge et betalingskort, der er udstedt i {OVERSEAS} eller {COUNTRY}.',
      et: 'Et hääletada {COUNTRY} nimel, on vaja maksekaarti, mis on väljastatud {OVERSEAS}-s või {COUNTRY}-s.',
      fi: 'Voidaksesi äänestää maan {COUNTRY} puolesta tarvitset maksukortin, joka on myönnetty maassa {OVERSEAS} tai {COUNTRY}.',
      fr: "Pour voter au nom de {COUNTRY}, vous aurez besoin d'une carte de paiement émise en {OVERSEAS} ou en {COUNTRY}.",
      ka: '{COUNTRY}-ის სახელით ხმის მისაცემად დაგჭირდებათ გადახდის ბარათი, რომელიც გაცემულია {OVERSEAS}-ში ან {COUNTRY}-ში.',
      de: 'Um Stimmen im Namen von {COUNTRY} abzugeben, benötigen Sie eine Zahlungskarte, die in {OVERSEAS} oder {COUNTRY} ausgestellt wurde.',
      el: 'Για να ψηφίσετε εκ μέρους της {COUNTRY}, θα χρειαστείτε μια κάρτα πληρωμής που έχει εκδοθεί σε {OVERSEAS} ή {COUNTRY}.',
      is: 'Til að greiða atkvæði fyrir hönd {COUNTRY} þarftu greiðslukort sem gefið er út í {OVERSEAS} eða {COUNTRY}.',
      ga: 'Chun vótaí a chaitheamh thar ceann {COUNTRY}, beidh cárta íocaíochta uait a eisíodh in {OVERSEAS} nó i {COUNTRY}.',
      he: 'כדי להצביע בשם {COUNTRY}, תזדקקו לכרטיס תשלום שהונפק ב{OVERSEAS} או ב{COUNTRY}.',
      it: 'Per votare per conto di {COUNTRY}, avrai bisogno di una carta di pagamento emessa in {OVERSEAS} o {COUNTRY}.',
      lv: 'Lai balsotu {COUNTRY} vārdā, jums būs nepieciešama maksājumu karte, kas izdota {OVERSEAS} vai {COUNTRY}.',
      lt: 'Norint balsuoti {COUNTRY} vardu, jums reikės mokėjimo kortelės, išduotos {OVERSEAS} arba {COUNTRY}.',
      lb: 'Fir am Numm vu(n) {COUNTRY} ofzestëmmen, braucht Dir eng Bezuelkaart, déi a(n) {OVERSEAS} oder a(n) {COUNTRY} ausgestallt gouf.',
      mt: "Sabiex titfa' voti f'isem {COUNTRY}, ser ikollok bżonn karta tal-ħlas li tkun inħarġet f'{OVERSEAS} jew f'{COUNTRY}.",
      cnr: 'Da biste glasali u ime {COUNTRY}, biće vam potrebna platna kartica izdata u {OVERSEAS} ili {COUNTRY}.',
      nl: 'Om namens {COUNTRY} te stemmen, heb je een betaalkaart nodig die is uitgegeven in {OVERSEAS} of {COUNTRY}.',
      no: 'For å avgi stemmer på vegne av {COUNTRY}, trenger du et betalingskort som er utstedt i {OVERSEAS} eller {COUNTRY}.',
      pl: 'Aby oddać głosy w imieniu {COUNTRY}, potrzebujesz karty płatniczej wydanej w {OVERSEAS} lub {COUNTRY}.',
      pt: 'Para votar em nome de {COUNTRY}, precisará de um cartão de pagamento emitido em {OVERSEAS} ou {COUNTRY}.',
      sr: 'Да бисте гласали у име {COUNTRY}, биће вам потребна платна картица издата у {OVERSEAS} или {COUNTRY}.',
      sl: 'Za glasovanje v imenu države {COUNTRY} potrebujete plačilno kartico, izdano v državi {OVERSEAS} ali {COUNTRY}.',
      es: 'Para votar en nombre de {COUNTRY}, necesitarás una tarjeta de pago emitida en {OVERSEAS} o {COUNTRY}.',
      sv: 'För att rösta för {COUNTRY} behöver du ett betalkort som är utfärdat i {OVERSEAS} eller {COUNTRY}.',
      uk: 'Щоб проголосувати від імені {COUNTRY}, вам знадобиться платіжна картка, видана в {OVERSEAS} або {COUNTRY}.',
    },
  },
}
