export const rounds = [
  {
    name: 'semi1',
    displayName: 'First Semi-Final',
    contestants: {
      upsert: [
        { ddi: { semi1: '01' } },
        { ddi: { semi1: '02' } },
        { ddi: { semi1: '03' } },
        { ddi: { semi1: '04' } },
        { ddi: { semi1: '05' } },
        { ddi: { semi1: '06' } },
        { ddi: { semi1: '07' } },
        { ddi: { semi1: '08' } },
        { ddi: { semi1: '09' } },
        { ddi: { semi1: '10' } },
        { ddi: { semi1: '11' } },
        { ddi: { semi1: '12' } },
        { ddi: { semi1: '13' } },
        { ddi: { semi1: '14' } },
        { ddi: { semi1: '15' } },
      ],
    },
    preShowtime: 1747087200000,
    showtime: 1747162800000,
  },
  {
    name: 'semi2',
    displayName: 'Second Semi-Final',
    contestants: {
      upsert: [
        { ddi: { semi2: '01' } },
        { ddi: { semi2: '02' } },
        { ddi: { semi2: '03' } },
        { ddi: { semi2: '04' } },
        { ddi: { semi2: '05' } },
        { ddi: { semi2: '06' } },
        { ddi: { semi2: '07' } },
        { ddi: { semi2: '08' } },
        { ddi: { semi2: '09' } },
        { ddi: { semi2: '10' } },
        { ddi: { semi2: '11' } },
        { ddi: { semi2: '12' } },
        { ddi: { semi2: '13' } },
        { ddi: { semi2: '14' } },
        { ddi: { semi2: '15' } },
        { ddi: { semi2: '16' } },
      ],
    },
    preShowtime: 1747260000000,
    showtime: 1747335600000,
  },
  {
    name: 'final',
    displayName: 'Grand Final',
    contestants: {
      upsert: [
        { ddi: { final: '01' } },
        { ddi: { final: '02' } },
        { ddi: { final: '03' } },
        { ddi: { final: '04' } },
        { ddi: { final: '05' } },
        { ddi: { final: '06' } },
        // { ddi: { final: '07' } },
        // { ddi: { final: '08' } },
        // { ddi: { final: '09' } },
        // { ddi: { final: '10' } },
        // { ddi: { final: '11' } },
        // { ddi: { final: '12' } },
      ],
    },
    preShowtime: 1747432800000,
    showtime: 1747508400000,
  },
]
