#!/bin/bash
podman run -t --rm --env LOCPATH=/usr/src/based-db/dist/locale -v "$PWD:/usr/src/based-db" based-db-clibs-build-linux_aarch64 \
sh -c '\. "/usr/local/nvm/nvm.sh"; cd /usr/src/based-db; $@' -- "$@"
