export const ERRORS = {
  OUT_OF_RANGE: 'Value is out of range',
  EXPECTED_VALUE_IN_ENUM: 'Expected value in "enum" field',
  EXPECTED_DATE: 'Expected number or Date',
  EXPECTED_BOOL: 'Expected boolean',
  EXPECTED_OBJ: 'Expected object',
  EXPECTED_ARR: 'Expected array',
  EXPECTED_NUM: 'Expected number',
  EXPECTED_STR: 'Expected string',
  EXPECTED_PRIMITIVE: 'Expected primitive value',
  INVALID_VALUE: 'Invalid value',
  INVALID_SCHEMA: 'Invalid schema',
  MIN_MAX: 'Max value must be larger than min value',
  UNKNOWN_PROP: 'Unknown property',
  MISSING_TYPE: 'Missing type',
} as const
