export default {
  locales: {
    en: { required: true },
    fr: { required: true },
    nl: { required: true },
    el: { required: true },
    he: { required: true },
    it: { required: true },
    lv: { required: true },
    lb: { required: true },
    ro: { required: true },
    sl: { required: true },
    es: { required: true },
    de: { required: true },
    cs: { required: true },
    et: { required: true },
  },
  props: {
    info: { type: 'string', format: 'html', localized: true },
    terms: {
      type: 'object',
      props: {
        title: { type: 'string', localized: true },
        introductionTitle: { type: 'string', localized: true },
        introductionText: { type: 'string', format: 'html', localized: true },
        rulesTitle: { type: 'string', localized: true },
        rulesText: { type: 'string', format: 'html', localized: true },
        procedureTitle: { type: 'string', localized: true },
        procedureText: { type: 'string', format: 'html', localized: true },
        noRefundsTitle: { type: 'string', localized: true },
        noRefundsText: { type: 'string', format: 'html', localized: true },
        dataTitle: { type: 'string', localized: true },
        dataText: { type: 'string', format: 'html', localized: true },
        voterRespTitle: { type: 'string', localized: true },
        voterRespText: { type: 'string', format: 'html', localized: true },
        votingWindowTitle: { type: 'string', localized: true },
        votingWindowText: { type: 'string', format: 'html', localized: true },
        generalCondTitle: { type: 'string', localized: true },
        generalCondText: { type: 'string', format: 'html', localized: true },
        jurisdictionTitle: { type: 'string', localized: true },
        jurisdictionText: { type: 'string', format: 'html', localized: true },
        changesTitle: { type: 'string', localized: true },
        changesText: { type: 'string', format: 'html', localized: true },
        lastUpdatedText: { type: 'string', format: 'html', localized: true },
        lastUpdated: { type: 'timestamp' },
      },
    },
    privacy: { type: 'string', format: 'html', localized: true },
    excludedCountries: { items: { ref: 'country' } },
    activeSequence: { ref: 'sequence' },
    coreDataLock: { type: 'boolean' },
    winner: { type: 'string' },
    dictionary: {
      type: 'object',
      props: {
        addVotes: { type: 'string', localized: true },
        appleMusic: { type: 'string', localized: true },
        appleMusicDisclaimer: { type: 'string', localized: true },
        buttonCall: { type: 'string', localized: true },
        buttonSMS: { type: 'string', localized: true },
        callNow: { type: 'string', localized: true },
        changeDescription: { type: 'string', localized: true },
        changeLocation: { type: 'string', localized: true },
        continue: { type: 'string', localized: true },
        cookieDisclaimer: { type: 'string', localized: true },
        imprint: { type: 'string', localized: true },
        overviewButton: { type: 'string', localized: true },
        phoneDescription: { type: 'string', localized: true },
        phoneInfo: { type: 'string', localized: true },
        phoneLocation: { type: 'string', localized: true },
        phoneSelection: { type: 'string', localized: true },
        privacy: { type: 'string', localized: true },
        selectionButton: { type: 'string', localized: true },
        selectionDescription: { type: 'string', localized: true },
        selectionSecure: { type: 'string', localized: true },
        selectionTitle: { type: 'string', localized: true },
        sendSMS: { type: 'string', localized: true },
        summaryButton: { type: 'string', localized: true },
        summaryCheckbox: { type: 'string', localized: true },
        summaryDisclaimer: { type: 'string', localized: true },
        summaryEmail: { type: 'string', localized: true },
        summaryProcessing: { type: 'string', localized: true },
        summaryProcessingMsg: { type: 'string', localized: true },
        summaryRefund: { type: 'string', localized: true },
        summarySecure: { type: 'string', localized: true },
        summarySelect: { type: 'string', localized: true },
        summaryTitle: { type: 'string', localized: true },
        summaryTotal: { type: 'string', localized: true },
        terms: { type: 'string', localized: true },
        thankYou: { type: 'string', localized: true },
        thankYouMax: { type: 'string', localized: true },
        thankYouMaxButton: { type: 'string', localized: true },
        thankYouOnline: { type: 'string', localized: true },
        thankYouOnlineButton: { type: 'string', localized: true },
        thankYouPhone: { type: 'string', localized: true },
        thankYouPhoneButton: { type: 'string', localized: true },
        votingInfo: { type: 'string', localized: true },
        whyImportant: { type: 'string', localized: true },
        days: { type: 'string', localized: true },
        hours: { type: 'string', localized: true },
        minutes: { type: 'string', localized: true },
        seconds: { type: 'string', localized: true },
      },
    },
    onboarding: {
      type: 'object',
      props: {
        restOfTheWorld: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        sanMarino: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        notAllowedSemi1: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        notAllowedSemi2: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        online: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        parentCode: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        phone: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        overseasCode: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
        noCode: {
          type: 'object',
          props: { title: { type: 'string', localized: true }, description: { type: 'string', localized: true } },
        },
      },
    },
  },
  types: {
    country: {
      props: {
        name: { type: 'alias' },
        currency: {
          enum: [
            'all',
            'amd',
            'aud',
            'azn',
            'chf',
            'czk',
            'dkk',
            'eur',
            'gbp',
            'gel',
            'ils',
            'isk',
            'mdl',
            'nok',
            'pln',
            'rsd',
            'sek',
            'uah',
          ],
        },
        isOverSeasTerritory: { type: 'boolean' },
        prequalifiedFor: { ref: 'round', prop: 'prequalifiedContries' },
        voteType: { enum: ['sms_text', 'sms_suffix', 'online', 'call_suffix'] },
        maxVotes: { type: 'uint8' },
        isTerritoryOf: { ref: 'country', prop: 'overseasTerritories' },
        price: { type: 'uint16' },
        destination: { type: 'string' },
        votingText: { type: 'string', localized: true },
        votingLegal: { type: 'string', localized: true },
        overseasTerritories: {
          items: { ref: 'country', prop: 'isTerritoryOf' },
        },
        votingRounds: {
          items: { ref: 'round', prop: 'canVote' },
        },
        contestants: {
          items: { ref: 'contestant', prop: 'country' },
        },
      },
    },
    sequence: {
      props: {
        name: { type: 'alias' },
        displayName: { type: 'string' },
        goLiveTime: { type: 'timestamp' },
        recapVideo: { ref: 'file', prop: 'sequenceRecapVideo' },
        recapTitle: { type: 'string', localized: true },
        title: { type: 'string', localized: true },
        description: { type: 'string', localized: true },
        countdown: { type: 'timestamp' },
        round: { ref: 'round', prop: 'sequences' },
        row: {
          props: {
            title: { type: 'string', localized: true },
            description: { type: 'string', localized: true },
            countdown: { type: 'timestamp' },
          },
        },
      },
    },
    round: {
      props: {
        name: { type: 'alias' },
        displayName: { type: 'string' },
        contestants: { items: { ref: 'contestant', prop: 'rounds' } },
        canVote: { items: { ref: 'country', prop: 'votingRounds' } },
        prequalifiedContries: {
          items: { ref: 'country', prop: 'prequalifiedFor' },
        },
        votes: { items: { ref: 'vote', prop: 'round' } },
        createdBy: { ref: 'user', prop: 'createdRounds' },
        sequences: {
          items: { ref: 'sequence', prop: 'round' },
        },
      },
    },
    contestant: {
      props: {
        name: { type: 'string' },
        ddi: { type: 'alias' },
        song: { type: 'string' },
        lyrics: { type: 'string' },
        country: { ref: 'country', prop: 'contestants' },
        image: { ref: 'file', prop: 'contestant_image' },
        video: { ref: 'file', prop: 'contestant_video' },
        thankYouVideos: { items: { ref: 'file', prop: 'contestant_ty_video' } },
        rounds: {
          items: { ref: 'round', prop: 'contestants' },
        },
      },
    },
    user: {
      props: {
        name: { type: 'string' },
        email: { type: 'alias', format: 'email' },
        role: { enum: ['admin', 'translator', 'viewer'] },
        translatorOf: { items: { ref: 'language', prop: 'translators' } },
        avatar: { ref: 'file', prop: 'avatarOf' },
        currentToken: { type: 'alias' },
        status: { enum: ['login', 'clear', 'invited'] },
        createdAt: { type: 'timestamp', on: 'create' },
        updatedAt: { type: 'timestamp', on: 'update' },
        invited: { items: { ref: 'user', prop: 'invitedBy' } },
        invitedBy: { ref: 'user', prop: 'invited' },
        inactive: { type: 'boolean' },
        createdRounds: {
          items: { ref: 'round', prop: 'createdBy' },
        },
      },
    },
    file: {
      props: {
        name: { type: 'string' },
        src: { type: 'string', format: 'URL' },
        mimeType: { type: 'string' },
        description: { type: 'string' },
        progress: { type: 'number', display: 'ratio' },
        status: { enum: ['uploading', 'transcoding', 'ready', 'error'] },
        statusText: { type: 'string' },
        size: { type: 'int32' },
        createdAt: { type: 'timestamp', on: 'create' },
        updatedAt: { type: 'timestamp', on: 'update' },
        thumbnail: { type: 'string', format: 'URL' },
        hls: { type: 'string', format: 'URL' },
        dash: { type: 'string', format: 'URL' },
        videoPreview: { type: 'string', format: 'URL' },
        selvaId: { type: 'alias' },
        sequenceRecapVideo: {
          items: { ref: 'sequence', prop: 'recapVideo' },
        },
        contestant_image: {
          items: { ref: 'contestant', prop: 'image' },
        },
        contestant_video: {
          items: { ref: 'contestant', prop: 'video' },
        },
        contestant_ty_video: {
          items: { ref: 'contestant', prop: 'thankYouVideos' },
        },
        items: { ref: 'user', prop: 'avatar' },
      },
    },
  },
  language: {
    props: {
      iso: { type: 'alias', required: true },
      name: { type: 'string' },
      completionStatus: { type: 'number', min: 0, max: 1 },
      translators: { items: { ref: 'user', prop: 'translatorOf' } },
    },
  },
  payment: {
    props: {
      confirmationTokenId: { type: 'string' },
      intentId: { type: 'alias' },
      fingerprint: { type: 'alias' },
      amount: { type: 'number' },
      currency: { type: 'string' },
      status: {
        enum: [
          'requested',
          'ready_for_payment',
          'intent_success',
          'intent_failed',
          'webhook_success',
          'webhook_failed',
          'capture_captured',
          'capture_canceled',
        ],
      },
      bankCountry: { type: 'string' },
      failReason: { type: 'string' },
      vote: { ref: 'vote', prop: 'payment' },
      createdAt: { type: 'timestamp', on: 'create' },
      updatedAt: { type: 'timestamp', on: 'update' },
    },
  },
  vote: {
    props: {
      fingerprintAndRound: { type: 'alias', required: true },
      payment: { ref: 'payment', prop: 'vote', required: true },
      round: { ref: 'round', prop: 'votes', required: true },
      ddi: {
        props: {
          ddi1: { type: 'uint8' },
          ddi2: { type: 'uint8' },
          ddi3: { type: 'uint8' },
          ddi4: { type: 'uint8' },
          ddi5: { type: 'uint8' },
          ddi6: { type: 'uint8' },
          ddi7: { type: 'uint8' },
          ddi8: { type: 'uint8' },
          ddi9: { type: 'uint8' },
          ddi10: { type: 'uint8' },
          ddi11: { type: 'uint8' },
          ddi12: { type: 'uint8' },
          ddi13: { type: 'uint8' },
          ddi14: { type: 'uint8' },
          ddi15: { type: 'uint8' },
          ddi16: { type: 'uint8' },
          ddi17: { type: 'uint8' },
          ddi18: { type: 'uint8' },
          ddi19: { type: 'uint8' },
          ddi20: { type: 'uint8' },
        },
      },
    },
  },
}
