import {
  TypeIndex,
  ALIAS,
  BINARY,
  JSON,
  BOOLEAN,
  CARDINALITY,
  TIMESTAMP,
  INT16,
  INT32,
  INT8,
  UINT8,
  UINT16,
  UINT32,
  NUMBER,
  ENUM,
  ID,
  MICRO_BUFFER,
  REFERENCE,
  REFERENCES,
  STRING,
  TEXT,
  ALIASES,
  VECTOR,
  COLVEC,
  WEAK_REFERENCE,
  WEAK_REFERENCES,
  NULL,
  OBJECT,
} from './types.js'

export const DEFAULT_MAP: Record<TypeIndex, any> = {
  [NULL]: 0,
  [OBJECT]: 0,
  [WEAK_REFERENCE]: 0,
  [WEAK_REFERENCES]: 0,
  [ALIAS]: '',
  [BINARY]: new Uint8Array(),
  [BOOLEAN]: false,
  [CARDINALITY]: [],
  [NUMBER]: 0,
  [TIMESTAMP]: 0,
  [ENUM]: 0,
  [ID]: 0,
  [INT16]: 0,
  [INT32]: 0,
  [INT8]: 0,
  [UINT8]: 0,
  [UINT16]: 0,
  [UINT32]: 0,
  [JSON]: null,
  [MICRO_BUFFER]: undefined,
  [REFERENCE]: undefined,
  [REFERENCES]: [],
  [STRING]: '',
  [ALIASES]: [],
  [TEXT]: {},
  [VECTOR]: undefined, // maybe not can set a vec with 0
  [COLVEC]: undefined, // maybe not can set a vec with 0
}
