name: Release
run-name: based-db CI/CD Release 🚀
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      notes:
        description: Release notes
        type: string
jobs:
  release-binaries:
    name: Release ${{inputs.version}} binaries
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        if: ${{ !inputs.version }}
        run: |
          echo "No version provided on inputs"
          exit 1
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: .
      - name: Create release
        run: |
          gh release create ${{inputs.version}} --title ${{inputs.version}} --target ${{github.ref}} Linux-X64-selvad-binaries/Linux_x64.tar.gz macOS-X64-selvad-binaries/Darwin_x64.tar.gz macOS-ARM64-selvad-binaries/Darwin_arm64.tar.gz --notes "${{inputs.notes}}" --draft --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
